// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dreamtree/seeds/v1/types.proto

package seeds

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters of the seeds module.
type Params struct {
	// max_commitment_bytes bounds the size of a commitment digest (hex/base64
	// string). A commitment is a hash or Merkle root, never a body, so this is
	// small by design. 0 means use the module default.
	MaxCommitmentBytes uint32 `protobuf:"varint,1,opt,name=max_commitment_bytes,json=maxCommitmentBytes,proto3" json:"max_commitment_bytes,omitempty"`
	// max_source_ref_bytes bounds the opaque origin reference length.
	MaxSourceRefBytes uint32 `protobuf:"varint,2,opt,name=max_source_ref_bytes,json=maxSourceRefBytes,proto3" json:"max_source_ref_bytes,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1441d3969325b6a2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxCommitmentBytes() uint32 {
	if m != nil {
		return m.MaxCommitmentBytes
	}
	return 0
}

func (m *Params) GetMaxSourceRefBytes() uint32 {
	if m != nil {
		return m.MaxSourceRefBytes
	}
	return 0
}

// Seed is a commitment anchored on-chain: the hash (or Merkle root) of a
// wallet record, an attestation, or any provenance-bearing body that lives in
// the data fabric. The body never enters consensus; only this commitment does.
type Seed struct {
	// id is the global monotonic sequence assigned at commit time.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// committer is the address that anchored this commitment.
	Committer string `protobuf:"bytes,2,opt,name=committer,proto3" json:"committer,omitempty"`
	// subject identifies what the commitment is about — typically the owning
	// wallet's DID (e.g. did:web:id.dreamtree.org:w:<uuid>). Free-form so the
	// knowledge graph and other producers can namespace their own subjects.
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// commitment is the hex-encoded digest (sha256 of a body, or a Merkle root
	// of a batch). This is the anchor; the body stays in the fabric.
	Commitment string `protobuf:"bytes,4,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// kind names what was committed: "record", "batch_root", "attestation",
	// "kg_claim", etc. Producers own their kinds.
	Kind string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	// source_ref is an opaque origin pointer (a roots record id, a batch label,
	// a gnosis observation id) — enough to locate the body off-chain.
	SourceRef string `protobuf:"bytes,6,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	// height is the block height at which this seed was committed.
	Height int64 `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	// committed_at is the block time (unix seconds) of the commit.
	CommittedAt int64 `protobuf:"varint,8,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
}

func (m *Seed) Reset()         { *m = Seed{} }
func (m *Seed) String() string { return proto.CompactTextString(m) }
func (*Seed) ProtoMessage()    {}
func (*Seed) Descriptor() ([]byte, []int) {
	return fileDescriptor_1441d3969325b6a2, []int{1}
}
func (m *Seed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Seed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Seed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Seed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seed.Merge(m, src)
}
func (m *Seed) XXX_Size() int {
	return m.Size()
}
func (m *Seed) XXX_DiscardUnknown() {
	xxx_messageInfo_Seed.DiscardUnknown(m)
}

var xxx_messageInfo_Seed proto.InternalMessageInfo

func (m *Seed) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Seed) GetCommitter() string {
	if m != nil {
		return m.Committer
	}
	return ""
}

func (m *Seed) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Seed) GetCommitment() string {
	if m != nil {
		return m.Commitment
	}
	return ""
}

func (m *Seed) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Seed) GetSourceRef() string {
	if m != nil {
		return m.SourceRef
	}
	return ""
}

func (m *Seed) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Seed) GetCommittedAt() int64 {
	if m != nil {
		return m.CommittedAt
	}
	return 0
}

// GenesisState is the seeds state provided at genesis.
type GenesisState struct {
	// params defines the module parameters.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// seeds is the set of anchored commitments (for export/import).
	Seeds []Seed `protobuf:"bytes,2,rep,name=seeds,proto3" json:"seeds"`
	// next_id is the sequence value the next commit will take.
	NextId uint64 `protobuf:"varint,3,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_1441d3969325b6a2, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetSeeds() []Seed {
	if m != nil {
		return m.Seeds
	}
	return nil
}

func (m *GenesisState) GetNextId() uint64 {
	if m != nil {
		return m.NextId
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "dreamtree.seeds.v1.Params")
	proto.RegisterType((*Seed)(nil), "dreamtree.seeds.v1.Seed")
	proto.RegisterType((*GenesisState)(nil), "dreamtree.seeds.v1.GenesisState")
}

func init() { proto.RegisterFile("dreamtree/seeds/v1/types.proto", fileDescriptor_1441d3969325b6a2) }

var fileDescriptor_1441d3969325b6a2 = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x63, 0xc7, 0x75, 0xc8, 0xa5, 0x20, 0xf5, 0x14, 0x95, 0x23, 0xa8, 0x26, 0x64, 0x40,
	0x51, 0xa5, 0xda, 0xb4, 0x48, 0x48, 0x54, 0x42, 0xa2, 0x61, 0x40, 0x6c, 0xc8, 0xd9, 0x58, 0x2c,
	0xdb, 0xf7, 0xea, 0x1c, 0x70, 0xbe, 0xc8, 0x77, 0x89, 0xdc, 0xaf, 0xd0, 0x09, 0x89, 0x4f, 0xc0,
	0xc6, 0xd8, 0x81, 0x0f, 0xd1, 0xb1, 0x62, 0x62, 0x42, 0x28, 0x19, 0xfa, 0x35, 0x90, 0xef, 0x9c,
	0xa4, 0x52, 0x58, 0xac, 0x7b, 0xef, 0xf7, 0xfe, 0xbe, 0xf7, 0xff, 0xeb, 0x90, 0x47, 0x0b, 0x88,
	0xb9, 0x2a, 0x00, 0x02, 0x09, 0x40, 0x65, 0x30, 0x3f, 0x0e, 0xd4, 0xc5, 0x14, 0xa4, 0x3f, 0x2d,
	0x84, 0x12, 0x18, 0xaf, 0xb9, 0xaf, 0xb9, 0x3f, 0x3f, 0xee, 0x75, 0x33, 0x91, 0x09, 0x8d, 0x83,
	0xea, 0x64, 0x26, 0x7b, 0x7b, 0x31, 0x67, 0xb9, 0x08, 0xf4, 0xb7, 0x6e, 0x3d, 0x4a, 0x85, 0xe4,
	0x42, 0x46, 0x66, 0xd6, 0x14, 0x06, 0x0d, 0x2e, 0x2d, 0xe4, 0x7e, 0x88, 0x8b, 0x98, 0x4b, 0xfc,
	0x1c, 0x75, 0x79, 0x5c, 0x46, 0xa9, 0xe0, 0x9c, 0x29, 0x0e, 0xb9, 0x8a, 0x92, 0x0b, 0x05, 0x92,
	0x58, 0x7d, 0x6b, 0x78, 0x3f, 0xc4, 0x3c, 0x2e, 0xdf, 0xae, 0xd1, 0xa8, 0x22, 0x38, 0x30, 0x0a,
	0x29, 0x66, 0x45, 0x0a, 0x51, 0x01, 0xe7, 0xb5, 0xc2, 0xd6, 0x8a, 0x3d, 0x1e, 0x97, 0x63, 0x8d,
	0x42, 0x38, 0xd7, 0x82, 0xd3, 0x83, 0xcb, 0xdb, 0xab, 0x43, 0xb2, 0xb1, 0x5a, 0xd6, 0x66, 0xcd,
	0x06, 0x83, 0x6f, 0x36, 0x72, 0xc6, 0x00, 0x14, 0x3f, 0x40, 0x36, 0xa3, 0xfa, 0x62, 0x27, 0xb4,
	0x19, 0xc5, 0x2f, 0x51, 0xdb, 0xac, 0xa5, 0xa0, 0xd0, 0x7f, 0x6f, 0x8f, 0xc8, 0xaf, 0x9f, 0x47,
	0xdd, 0xda, 0xca, 0x19, 0xa5, 0x05, 0x48, 0x39, 0x56, 0x05, 0xcb, 0xb3, 0x70, 0x33, 0x8a, 0x09,
	0x6a, 0xc9, 0x59, 0xf2, 0x09, 0x52, 0x45, 0x9a, 0x95, 0x2a, 0x5c, 0x95, 0xd8, 0x43, 0x68, 0x63,
	0x94, 0x38, 0x1a, 0xde, 0xe9, 0x60, 0x8c, 0x9c, 0xcf, 0x2c, 0xa7, 0x64, 0x47, 0x13, 0x7d, 0xc6,
	0x07, 0x08, 0x6d, 0xac, 0x12, 0x57, 0x93, 0xb6, 0x5c, 0x39, 0xc4, 0xfb, 0xc8, 0x9d, 0x00, 0xcb,
	0x26, 0x8a, 0xb4, 0xfa, 0xd6, 0xb0, 0x19, 0xd6, 0x15, 0x7e, 0x8a, 0x76, 0x57, 0x1b, 0xd1, 0x28,
	0x56, 0xe4, 0x9e, 0xa6, 0x9d, 0x75, 0xef, 0x4c, 0x9d, 0x3e, 0xae, 0x72, 0xd9, 0xdf, 0xce, 0xa5,
	0x0a, 0x63, 0xf0, 0xdd, 0x42, 0xbb, 0xef, 0x20, 0x07, 0xc9, 0xe4, 0x58, 0xc5, 0x0a, 0xf0, 0x6b,
	0xe4, 0x4e, 0x75, 0x60, 0x3a, 0xa1, 0xce, 0x49, 0xcf, 0xdf, 0x7e, 0x1c, 0xbe, 0x89, 0x74, 0xd4,
	0xbe, 0xfe, 0xf3, 0xa4, 0xf1, 0xe3, 0xf6, 0xea, 0xd0, 0x0a, 0x6b, 0x11, 0x7e, 0x85, 0x76, 0xf4,
	0x14, 0xb1, 0xfb, 0xcd, 0x61, 0xe7, 0x84, 0xfc, 0x4f, 0x5d, 0x5d, 0x7c, 0x57, 0x6b, 0x14, 0xf8,
	0x21, 0x6a, 0xe5, 0x50, 0xaa, 0x88, 0x51, 0x9d, 0xa7, 0x13, 0xba, 0x55, 0xf9, 0x9e, 0x8e, 0xde,
	0x5c, 0x2f, 0x3c, 0xeb, 0x66, 0xe1, 0x59, 0x7f, 0x17, 0x9e, 0xf5, 0x75, 0xe9, 0x35, 0x6e, 0x96,
	0x5e, 0xe3, 0xf7, 0xd2, 0x6b, 0x7c, 0x7c, 0x96, 0x31, 0x35, 0x99, 0x25, 0x7e, 0x2a, 0x78, 0x90,
	0x7c, 0x11, 0x79, 0x76, 0x44, 0x61, 0x1e, 0x6c, 0x59, 0x4d, 0x5c, 0xfd, 0x1e, 0x5f, 0xfc, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0xf4, 0xbc, 0x7f, 0xbd, 0x09, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxSourceRefBytes != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxSourceRefBytes))
		i--
		dAtA[i] = 0x10
	}
	if m.MaxCommitmentBytes != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxCommitmentBytes))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Seed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Seed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Seed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CommittedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CommittedAt))
		i--
		dAtA[i] = 0x40
	}
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x38
	}
	if len(m.SourceRef) > 0 {
		i -= len(m.SourceRef)
		copy(dAtA[i:], m.SourceRef)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SourceRef)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Kind) > 0 {
		i -= len(m.Kind)
		copy(dAtA[i:], m.Kind)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Kind)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Committer) > 0 {
		i -= len(m.Committer)
		copy(dAtA[i:], m.Committer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Committer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NextId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Seeds) > 0 {
		for iNdEx := len(m.Seeds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Seeds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxCommitmentBytes != 0 {
		n += 1 + sovTypes(uint64(m.MaxCommitmentBytes))
	}
	if m.MaxSourceRefBytes != 0 {
		n += 1 + sovTypes(uint64(m.MaxSourceRefBytes))
	}
	return n
}

func (m *Seed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Committer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Kind)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SourceRef)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	if m.CommittedAt != 0 {
		n += 1 + sovTypes(uint64(m.CommittedAt))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Seeds) > 0 {
		for _, e := range m.Seeds {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.NextId != 0 {
		n += 1 + sovTypes(uint64(m.NextId))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCommitmentBytes", wireType)
			}
			m.MaxCommitmentBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCommitmentBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSourceRefBytes", wireType)
			}
			m.MaxSourceRefBytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSourceRefBytes |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Seed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Seed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Seed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Committer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Committer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kind = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceRef", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceRef = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommittedAt", wireType)
			}
			m.CommittedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommittedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seeds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seeds = append(m.Seeds, Seed{})
			if err := m.Seeds[len(m.Seeds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextId", wireType)
			}
			m.NextId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
