-- Connections seed data
-- Maps CSV schema to DB schema

INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100000, 'internal', 'connection_100000', '{"instructions": ["tagged for jobs and education", "populate item from 1.a"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100001, 'internal', 'connection_100001', '{"instructions": ["internal association tagging", "fuzzy search skills - verbs - from 1.b - select true"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100002, 'internal', 'connection_100002', '{"instructions": ["mastery slider 1-5", "internal association tagging - skills to experiences"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100003, 'internal', 'connection_100003', '{"instructions": ["2a-2i select 3", "selection 1"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100004, 'internal', 'connection_100004', '{"instructions": ["selection 2"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100005, 'internal', 'connection_100005', '{"instructions": ["selection 3"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100006, 'internal', 'connection_100006', '{"instructions": ["skills_mapping fuzzy search existing skills to each soared story", "confirm & build list"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100007, 'internal', 'connection_100007', '{"instructions": ["mastery slider 1-5", "internal association tagging - skills to experiences", "bucketing tool -- this is new -- drag and drop into 5 vertical buckets most to least -- list on the left buckets on the right", "auto-pop top 10 transferable skills"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100008, 'internal', 'connection_100008', '{"instructions": ["fetch and present the associated MBTI explanation text", "present remaining chars"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100009, 'internal', 'connection_100009', '{"instructions": ["present selectable pills of defined soft skills from this activity", "present populated ranking grid", "present top 10 transferable skills", "drag and drop SMS to each TS"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100010, 'internal', 'connection_100010', '{"instructions": ["present each textarea from 5 for editing, and confirmation", "populate with employment history", "iterate list builder", "populate education history", "iterate list builder"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100011, 'internal', 'connection_100011', '{"instructions": ["ideation resource", "populate with every skill from knowledges", "mastery slider 1-5"]}', 'Auto-generated - needs refinement');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100012, 'forward', 'hydrate_top_skills_by_mastery', '{"source": "transferable_skills", "filter": "top_10_by_mastery", "from_exercises": ["1.1.1.1", "1.1.1.2", "1.1.1.3", "1.1.1.4"]}', 'Populate top 10 transferable skills by mastery rating for ranking');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100013, 'forward', 'hydrate_jobs_from_entry', '{"source": "employment_history", "from_exercise": "1.1.1.1"}', 'Populate job list from earlier entry for work environment reflection');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100014, 'forward', 'hydrate_energizing_topics', '{"source": "flow_tracking", "filter": "high_energy_high_captivation", "from_module": "1.3"}', 'Populate energizing/captivating topics for Idea Tree starting words');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100015, 'forward', 'hydrate_compass_light', '{"source": "values_compass", "from_exercise": "2.1.3"}', 'Populate compass/light values for story coherence reference');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100016, 'resource', 'hydrate_skills_reference', '{"target": "skills_master", "display": "inline"}', 'Link to skills reference list');
INSERT INTO connections (id, connection_type, data_object, transform, implementation_notes) VALUES (100017, 'forward', 'hydrate_experiences_list', '{"source": "all_experiences", "from_module": "1.1"}', 'Populate complete list of experiences from Module 1');
