-- prompts
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100000', 'a) A time when you had an impact', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100001', 'b) A time you did something no one else around could have done', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100002', 'c) A time when you were genuinely excited', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100003', 'd) A time when you impressed yourself', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100004', 'e) A time when everything went according to plan', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100005', 'f) A time when nothing went according to plan', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100006', 'g) A time when you loved what you were doing', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100007', 'h) A time you did something you would like to do again', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100008', 'i) A time you did something you would not normally do', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100009', 'j) Any other story which represents your skillset', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100010', 'Write your four letter MBTI code here:', 'text_input', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100011', 'Introverts are more likely to be energized by alone time, be more private, keep their thoughts to themselves, and listen before speaking.', 'slider', '{"labels": ["e", "i"]}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100012', 'Intuitives tend to be concerned with innovation and what is possible. They tend to be more figurative and are oriented towards the future.', 'slider', '{"labels": ["s", "n"]}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100013', 'Feelers are likely to be most concerned with harmony, empathizing with involved parties with tact when making decisions. May be seen as overemotional, valuing all feelings equally.', 'slider', '{"labels": ["t", "f"]}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100014', 'Perceivers prefer to keep their options open and thrive when adapting to new situations. They often view time and deadlines as elastic.', 'slider', '{"labels": ["j", "p"]}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100015', '2. These are the remaining characteristics, strengths, or weaknesses which match your MBTI type, but you didn''t select above. Reflect and explain why they are false.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100016', '(possibly from your written stories)', 'textarea', '{"raw": "list builder"}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100017', 'a) If you do, write that here. If not, write down the characteristics of a place that you might want to live. (ex. by the ocean, has an active nightlife, quiet, access to nature, etc.)', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100018', 'b) What are your location restraints?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100019', 'c) Do you need to live in a specific country?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100020', 'd) Do you need to stay close to your family?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100021', 'e) Do you have medical needs?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100022', '-Are there any which excel in multiple?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100023', '-Write down your ranked list of location traits and ask 10-20 people if they know of anywhere which has those traits. Write down their ideas. ALWAYS thank them for their time and effort.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100024', '-Are there any locations which excel in multiple traits?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100025', '-Research each of the locations which embody multiple of your desired traits.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100026', '-Do number 4 together. Compare your findings. Discuss honestly. Agree upon ten possible locations. Rank together.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100027', 'Pay the most attention to, make a special note of, your top 3 locations.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100028', 'Consider the above. Describe your ideal workplace.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100029', 'a) How does the office look?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100030', 'b) What is nearby?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100031', 'c) Are there any important features?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100032', 'd) What part of the city or town is best?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100033', 'e) Is it near child care?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100034', 'f) What else can you think of?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100035', 'Recall any time when you were particularly productive. The production can be from your education, the stories you wrote before, or work experience. Who was directing you? Were you serving anyone (client, etc.)?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100036', 'What types of people do you want to work with?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100037', 'Do you prefer to work in teams, pairs, or alone?', 'radio', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100038', 'What types of people do you want to work for?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100039', 'Who in this world do you want to serve with your work?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100040', '– Salary (aggregate pay per year or month, regardless of hours worked)', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100041', '– Hourly (pay for time worked)', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100042', '– Contracting (pay agreed upon per project, typical for freelancers)', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100043', '– Commission (% of sale per sale)', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100044', '– Combination of above, or Other (specify)', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100045', 'If you feel the need to be more specific, do so here.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100046', 'Is there any activity, task, or skill which you find both highly energizing and highly captivating?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100047', 'Write a short description of each activity on the lines provided.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100048', 'Are there any activities which you find both highly energizing and highly captivating?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100049', 'Write a short description of each activity on the lines provided.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100050', 'Are there any activities which you find both highly energizing and highly captivating?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100051', 'What stories from your childhood have helped shape who you are today?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100052', 'What family relationships have had particularly significant impacts upon your beliefs?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100053', 'Do you have any elderly family members you care for or support? How does this shape your needs?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100054', 'Do you have any children you care for or support? How does this shape your needs?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100055', 'Do you have any family members or stories which inspire you? If so, give details.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100056', 'What are the most significant lessons your family has taught you?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100057', 'What group, or groups, do you identify with?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100058', 'Are you involved in any organizations, religious groups, neighborhood associations, group of friends, gaming club, or other regularly organized social events?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100059', 'Why are you involved in those groups?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100060', 'Do you have any personal goals concerning your community?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100061', 'Is there anything that might cause you to leave your community?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100062', 'Are there any worldly issues that are important to you? What are they?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100063', 'What are some lessons people should learn from history?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100064', 'Are there any worldly problems which you feel the need to help solve?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100065', 'Have you ever traveled outside of your country? Your continent?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100066', 'What have you learned from other cultures of the world?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100067', 'What do you think the world will look like in 10 years?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100068', '… 50 years?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100069', '… 100 years?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100070', 'They say that you are your own hardest critic. Critique yourself. What can you do better?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100071', 'What are your strengths?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100072', 'Do you have an idea or memory which makes you feel most like yourself? If so, describe it.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100073', 'What do you love about yourself?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100074', 'What major life events have shaped you? Briefly describe them.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100075', 'What is your greatest gift?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100076', 'Are you willing to do what needs to be done?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100077', 'Choose a skill to practice.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100078', 'Dedicate at least 15 minutes of singular focus to improving that skill every single day.', 'checkbox', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100079', 'Practice the skill every single day. Don''t stop.', 'checkbox', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100080', 'If you grow tired of practicing this skill, reach a level of mastery, or otherwise, choose another skill and repeat the process. This is the never-ending task of self-betterment.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100081', 'Who do you look up to? Who is your role model? Why?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100082', 'What do you admire about that person (or those people)? What characteristics do they have that make them special?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100083', 'What promises do you need to keep? To yourself? To those you care about?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100084', 'What has stopped you from keeping those promises?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100085', 'Forgive yourself when you mess up. If you fall off the horse, focus on getting back on the horse, not on the fact that you fell off. Forgive. Take yourself seriously, if you don''t, who will? Next.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100086', 'Sharpening your sword – choosing a useful and enjoyable skill to hone, practice, and sharpen as a way to stand out from your peers and, more importantly, to better yourself.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100087', 'Mindfulness – set aside a short amount of time to practice quieting your mind each day.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100088', '1. Work', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100089', '', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100090', '2. Play', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100091', '', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100092', '3. Love', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100093', '', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100094', '4. Health', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100095', '', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100096', '5. Overall, how are you?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100097', '', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100098', '1. What does work mean to you?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100099', '2. Why do you work?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100100', '3. Why do other people work?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100101', '4. What is the purpose of people working?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100102', '5. Other than money, what is gained from work?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100103', '6. Are honor, growth, or fulfillment essential to work? Explain.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100104', '7. What work would you do if all your needs were guaranteed?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100105', '1. Is there a meaning of life? Give details.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100106', '2. What is the meaning of your life?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100107', '3. Why do we exist?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100108', '4. What is good?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100109', '5. What is evil?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100110', '6. What is happiness?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100111', '7. Is there a higher being?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100112', '8. Why do we experience pain and suffering?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100113', '9. Is there some deeper meaning, mission, or purpose to life?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100114', '10. What injustices are there in the world?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100115', '1. Where do your two value systems support each other?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100116', '2. Where do they disagree?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100117', '3. Is one more important to you than the other? Which one? Why?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100118', '4. In your own words, explain how your work values and your life values work together.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100119', '1. Find a character from a book, series, movie, or real life for each mindset. The mindset should be that character''s defining quality.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100120', '2. Defend your choices. Explain how and why these characters exemplify the mindset. Give examples.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100121', '3. What does embodying the mindset help the character to accomplish?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100122', '1. What do you need to survive?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100123', '2. How would a comfortable life for you look?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100124', '3. What does happiness mean to you?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100125', '4. What is your definition of success?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100126', '5. If you had three wishes, what would they be?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100127', '6. Describe your dream life.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100128', '7. What are you willing to do to achieve your standards?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100129', '8. What strikes fear into your bones?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100130', '9. Detail some actions you think you could take to conquer those fears.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100131', '10. What situation over the next year are you afraid of failing?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100132', '11. Give three opportunistic perspectives on that situation.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100133', '12. Brainstorm actions you could take to excel in that situation.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100134', '13. Describe a time you overcame your fear.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100135', '14. Have you ever had an authority figure who motivated you? What about that person motivated you?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100136', '15. What is the worst possible situation you can accept for your life?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100137', '16. Describe the last time you were down. (Financially, emotionally, in performance, you choose your frame)', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100138', '17. What did you do to improve your situation?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100139', '18. What could you have done better?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100140', '1.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100141', '2.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100142', '3.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100143', 'Then, once you have designed a timeline, give this life option, this branch of your tree, a complete and accurate title. Describe your potential life in a way that suits you now, your roots, and this future.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100144', 'a. time – do you have the time to pull this off?', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100145', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100146', 'b. Funding – do you need any additional funds, are there any financial risks you are taking?', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100147', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100148', 'c. Skills – do you already have all the necessary skills, or are there some you still need to learn?', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100149', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100150', 'd. Contacts – do you know anyone doing this? Do you know anyone in the industry?', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100151', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100152', '2. Excitement – are you excited about this prospect? When you imagine this life unfolding in front of you, how does it make you feel?', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100153', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100154', '3. Confidence – How confident are you in this prospect?', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100155', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100156', '4. Coherence – How in line with your work values and your life values is this idea?', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100157', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100158', '5. Work Needs – consider your work priorities and all the pieces from Part 1. Does this idea support your roots? Consider location, financial needs, and any other areas of importance to you.', 'slider', '{"min": 1, "max": 10}', 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100159', '', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100160', '6. Discovery – what will you learn from this journey? What is the impact of choosing this path?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100161', 'What do you want to achieve by telling your story?', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100162', 'Brainstorm, make notes and generate ideas now.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100163', 'In 10 words or less, what is the theme or meaning that ties your life together?', 'text_input', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100164', '- Quickly jot down emotions, adjectives, and other vital descriptors associated with each story', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100165', '- Describe the life lesson you learned in every story, using six words or less for each', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100166', '- How does each of these life lessons tie into the theme of your life? Be explicit.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100167', '- Record 2-5 times you built a fantastic rapport with someone', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100168', 'The first story is your identity story. Not an autobiography. It should be about 1 page typed and needs to make sense of your values, work history, future goals, and your life mission. It is the story you tell yourself, the ideal which you try to live by. We will build off of this story to create your resume, elevator pitch, and your general presentation, it does not need to be any of those yet. Explain your roots, how they made you who you are, and how you have grown into an intentional and capable person that you are today. You may not feel as though you have a cohesive story. This is your opportunity to create that story. Take your time and revisit this task occasionally. To move forward in the process, you need to have an explicitly written identity. Write your story now.', 'textarea', NULL, 1, 1);
INSERT INTO prompts (id, prompt_text, input_type, input_config, version, is_active) VALUES ('100169', '• Consistency: Is the story consistent with the way you conduct your life now?', 'textarea', NULL, 1, 1);

-- stem
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100000', 1, 0, 0, 0, 1, 'content', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100001', 1, 0, 0, 0, 2, 'content', 100001, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100002', 1, 0, 0, 0, 3, 'content', 100002, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100003', 1, 0, 0, 0, 4, 'content', 100003, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100004', 1, 0, 0, 0, 5, 'content', 100004, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100005', 1, 0, 0, 0, 6, 'content', 100005, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100006', 1, 0, 0, 0, 7, 'content', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100007', 1, 0, 0, 0, 8, 'content', 100007, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100008', 1, 0, 0, 0, 9, 'content', 100008, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100009', 1, 1, 0, 0, 10, 'content', 100009, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100010', 1, 1, 0, 0, 11, 'content', 100010, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100011', 1, 1, 0, 0, 12, 'content', 100011, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100012', 1, 1, 0, 0, 13, 'content', 100012, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100013', 1, 1, 0, 0, 14, 'content', 100013, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100014', 1, 1, 0, 0, 15, 'content', 100014, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100015', 1, 1, 0, 0, 16, 'content', 100015, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100016', 1, 1, 0, 0, 17, 'content', 100016, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100017', 1, 1, 0, 0, 18, 'content', 100017, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100018', 1, 1, 0, 0, 19, 'content', 100018, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100019', 1, 1, 0, 0, 20, 'content', 100019, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100020', 1, 1, 0, 0, 21, 'content', 100020, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100021', 1, 1, 0, 0, 22, 'content', 100021, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100022', 1, 1, 0, 0, 23, 'content', 100022, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100023', 1, 1, 0, 0, 24, 'content', 100023, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100024', 1, 1, 1, 0, 25, 'content', 100024, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100025', 1, 1, 1, 1, 26, 'content', 100025, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100026', 1, 1, 1, 1, 27, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100027', 1, 1, 1, 2, 28, 'content', 100026, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100028', 1, 1, 1, 2, 29, 'tool', 100000, 100000);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100029', 1, 1, 1, 3, 30, 'content', 100027, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100030', 1, 1, 1, 3, 31, 'tool', 100000, 100001);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100031', 1, 1, 2, 0, 32, 'content', 100028, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100032', 1, 1, 2, 1, 33, 'content', 100029, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100033', 1, 1, 2, 1, 34, 'prompt', 100000, 100002);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100034', 1, 1, 2, 2, 35, 'content', 100030, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100035', 1, 1, 2, 2, 36, 'prompt', 100001, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100036', 1, 1, 2, 3, 37, 'content', 100031, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100037', 1, 1, 2, 3, 38, 'prompt', 100002, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100038', 1, 1, 2, 4, 39, 'content', 100032, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100039', 1, 1, 2, 4, 40, 'prompt', 100003, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100040', 1, 1, 2, 5, 41, 'content', 100033, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100041', 1, 1, 2, 5, 42, 'prompt', 100004, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100042', 1, 1, 2, 6, 43, 'content', 100034, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100043', 1, 1, 2, 6, 44, 'prompt', 100005, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100044', 1, 1, 2, 7, 45, 'content', 100035, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100045', 1, 1, 2, 7, 46, 'prompt', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100046', 1, 1, 2, 8, 47, 'content', 100036, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100047', 1, 1, 2, 8, 48, 'prompt', 100007, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100048', 1, 1, 2, 9, 49, 'content', 100037, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100049', 1, 1, 2, 9, 50, 'prompt', 100008, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100050', 1, 1, 2, 10, 51, 'content', 100038, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100051', 1, 1, 2, 10, 52, 'prompt', 100009, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100052', 1, 1, 3, 0, 53, 'content', 100039, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100053', 1, 1, 3, 0, 54, 'content', 100040, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100054', 1, 1, 3, 0, 55, 'content', 100041, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100055', 1, 1, 3, 0, 56, 'content', 100042, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100056', 1, 1, 3, 0, 57, 'content', 100043, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100057', 1, 1, 3, 0, 58, 'content', 100044, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100058', 1, 1, 3, 0, 59, 'content', 100045, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100059', 1, 1, 3, 2, 60, 'tool', 100001, 100003);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100060', 1, 1, 3, 3, 61, 'tool', 100001, 100004);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100061', 1, 1, 3, 4, 62, 'tool', 100001, 100005);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100062', 1, 1, 4, 0, 63, 'content', 100046, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100063', 1, 1, 4, 0, 64, 'tool', 100000, 100006);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100064', 1, 1, 5, 0, 65, 'connection', NULL, 100012);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100065', 1, 1, 6, 0, 66, 'content', 100611, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100066', 1, 1, 7, 0, 67, 'content', 100049, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100067', 1, 1, 7, 0, 68, 'tool', 100003, 100007);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100068', 1, 1, 7, 0, 69, 'content', 100050, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100069', 1, 1, 7, 0, 70, 'content', 100051, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100070', 1, 1, 7, 0, 71, 'content', 100052, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100071', 1, 1, 7, 0, 72, 'content', 100053, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100072', 1, 1, 7, 0, 73, 'content', 100054, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100073', 1, 1, 7, 0, 74, 'content', 100055, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100074', 1, 1, 7, 0, 75, 'content', 100056, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100075', 1, 1, 7, 0, 76, 'content', 100057, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100076', 1, 1, 7, 0, 77, 'content', 100058, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100077', 1, 1, 7, 0, 78, 'content', 100059, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100078', 1, 1, 7, 0, 79, 'content', 100060, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100079', 1, 1, 7, 0, 80, 'content', 100061, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100080', 1, 1, 7, 0, 81, 'content', 100062, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100081', 1, 1, 7, 0, 82, 'content', 100063, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100082', 1, 1, 7, 0, 83, 'content', 100064, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100083', 1, 1, 7, 0, 84, 'content', 100065, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100084', 1, 1, 7, 0, 85, 'prompt', 100010, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100085', 1, 1, 7, 0, 86, 'content', 100066, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100086', 1, 1, 7, 0, 87, 'content', 100067, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100087', 1, 1, 7, 0, 88, 'content', 100068, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100088', 1, 1, 7, 0, 89, 'content', 100069, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100089', 1, 1, 7, 0, 90, 'prompt', 100011, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100090', 1, 1, 7, 0, 91, 'content', 100070, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100091', 1, 1, 7, 0, 92, 'content', 100071, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100092', 1, 1, 7, 0, 93, 'prompt', 100012, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100093', 1, 1, 7, 0, 94, 'content', 100072, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100094', 1, 1, 7, 0, 95, 'content', 100073, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100095', 1, 1, 7, 0, 96, 'prompt', 100013, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100096', 1, 1, 7, 0, 97, 'content', 100074, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100097', 1, 1, 7, 0, 98, 'content', 100075, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100098', 1, 1, 7, 0, 99, 'prompt', 100014, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100099', 1, 1, 7, 0, 100, 'content', 100076, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100100', 1, 1, 7, 0, 101, 'content', 100077, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100101', 1, 1, 1, 0, 102, 'content', 100078, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100102', 1, 1, 1, 1, 103, 'content', 100079, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100103', 1, 1, 1, 1, 104, 'content', 100080, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100104', 1, 1, 1, 2, 105, 'content', 100081, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100105', 1, 1, 1, 2, 106, 'content', 100082, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100106', 1, 1, 1, 3, 107, 'content', 100083, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100107', 1, 1, 1, 3, 108, 'content', 100084, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100108', 1, 1, 2, 0, 109, 'content', 100085, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100109', 1, 1, 2, 0, 110, 'prompt', 100015, 100008);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100110', 1, 1, 3, 0, 111, 'content', 100086, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100111', 1, 1, 3, 0, 112, 'content', 100087, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100112', 1, 1, 4, 0, 113, 'content', 100088, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100113', 1, 1, 5, 0, 114, 'content', 100089, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100114', 1, 1, 5, 0, 115, 'content', 100090, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100115', 1, 1, 5, 0, 116, 'prompt', 100016, 100009);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100116', 1, 1, 6, 0, 117, 'content', 100091, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100117', 1, 1, 6, 0, 118, 'content', 100092, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100118', 1, 1, 6, 0, 119, 'content', 100093, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100119', 1, 1, 6, 0, 120, 'content', 100094, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100120', 1, 1, 6, 0, 121, 'content', 100095, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100121', 1, 1, 6, 0, 122, 'content', 100096, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100122', 1, 1, 6, 0, 123, 'content', 100097, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100123', 1, 1, 6, 0, 124, 'content', 100098, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100124', 1, 1, 6, 0, 125, 'content', 100099, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100125', 1, 1, 6, 0, 126, 'content', 100100, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100126', 1, 1, 6, 0, 127, 'content', 100101, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100127', 1, 1, 1, 0, 128, 'content', 100102, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100128', 1, 1, 2, 0, 129, 'content', 100103, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100129', 1, 1, 3, 0, 130, 'content', 100104, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100130', 1, 1, 3, 1, 131, 'content', 100105, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100131', 1, 1, 3, 1, 132, 'tool', 100000, 100010);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100132', 1, 1, 3, 2, 133, 'content', 100106, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100133', 1, 1, 3, 2, 134, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100134', 1, 1, 3, 3, 135, 'content', 100107, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100135', 1, 1, 3, 3, 136, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100136', 1, 1, 3, 4, 137, 'content', 100108, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100137', 1, 1, 3, 4, 138, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100138', 1, 1, 4, 0, 139, 'content', 100109, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100139', 1, 1, 4, 0, 140, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100140', 1, 1, 5, 0, 141, 'content', 100110, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100141', 1, 2, 0, 0, 142, 'content', 100111, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100142', 1, 2, 0, 0, 143, 'content', 100112, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100143', 1, 2, 0, 0, 144, 'content', 100113, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100146', 1, 2, 0, 0, 145, 'content', 100116, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100147', 1, 2, 0, 0, 146, 'content', 100117, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100148', 1, 2, 0, 0, 147, 'content', 100118, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100149', 1, 2, 0, 0, 148, 'content', 100119, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100150', 1, 2, 0, 0, 149, 'content', 100120, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100151', 1, 2, 0, 0, 150, 'content', 100121, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100152', 1, 2, 0, 0, 151, 'content', 100122, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100153', 1, 2, 0, 1, 152, 'content', 100123, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100154', 1, 2, 0, 1, 153, 'prompt', 100017, 100011);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100155', 1, 2, 0, 2, 154, 'content', 100124, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100156', 1, 2, 0, 2, 155, 'prompt', 100018, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100157', 1, 2, 0, 3, 156, 'content', 100125, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100158', 1, 2, 0, 3, 157, 'prompt', 100019, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100159', 1, 2, 0, 4, 158, 'content', 100126, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100160', 1, 2, 0, 4, 159, 'prompt', 100020, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100161', 1, 2, 0, 5, 160, 'content', 100127, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100162', 1, 2, 0, 5, 161, 'prompt', 100021, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100163', 1, 2, 0, 5, 162, 'content', 100128, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100164', 1, 2, 0, 1, 163, 'content', 100129, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100165', 1, 2, 0, 1, 164, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100166', 1, 2, 0, 2, 165, 'content', 100130, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100167', 1, 2, 0, 2, 166, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100168', 1, 2, 0, 3, 167, 'content', 100131, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100169', 1, 2, 0, 3, 168, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100170', 1, 2, 0, 4, 169, 'content', 100132, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100171', 1, 2, 0, 4, 170, 'tool', 100003, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100172', 1, 2, 0, 4, 171, 'content', 100133, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100173', 1, 2, 0, 1, 172, 'content', 100134, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100174', 1, 2, 0, 1, 173, 'content', 100135, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100175', 1, 2, 0, 1, 174, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100176', 1, 2, 0, 1, 175, 'content', 100136, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100177', 1, 2, 0, 1, 176, 'prompt', 100022, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100178', 1, 2, 0, 1, 177, 'content', 100137, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100179', 1, 2, 0, 1, 178, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100180', 1, 2, 0, 2, 179, 'content', 100138, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100181', 1, 2, 0, 2, 180, 'content', 100139, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100182', 1, 2, 0, 2, 181, 'prompt', 100023, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100183', 1, 2, 0, 2, 182, 'content', 100140, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100184', 1, 2, 0, 2, 183, 'prompt', 100024, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100185', 1, 2, 0, 2, 184, 'content', 100141, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100186', 1, 2, 0, 2, 185, 'prompt', 100025, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100187', 1, 2, 0, 2, 186, 'content', 100142, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100188', 1, 2, 0, 2, 187, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100189', 1, 2, 0, 2, 188, 'content', 100143, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100190', 1, 2, 0, 2, 189, 'tool', 100003, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100191', 1, 2, 0, 2, 190, 'content', 100144, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100192', 1, 2, 0, 2, 191, 'content', 100145, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100193', 1, 2, 0, 2, 192, 'content', 100146, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100194', 1, 2, 0, 2, 193, 'content', 100147, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100195', 1, 2, 0, 2, 194, 'content', 100148, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100196', 1, 2, 0, 2, 195, 'tool', 100003, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100197', 1, 2, 0, 2, 196, 'content', 100149, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100198', 1, 2, 0, 2, 197, 'content', 100150, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100199', 1, 2, 0, 2, 198, 'prompt', 100026, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100200', 1, 2, 0, 2, 199, 'content', 100151, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100201', 1, 2, 0, 2, 200, 'prompt', 100027, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100202', 1, 2, 0, 2, 201, 'content', 100152, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100203', 1, 2, 0, 2, 202, 'content', 100153, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100204', 1, 2, 0, 2, 203, 'content', 100154, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100205', 1, 2, 0, 2, 204, 'content', 100155, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100206', 1, 2, 0, 1, 205, 'content', 100156, 100013);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100207', 1, 2, 0, 1, 206, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100208', 1, 2, 0, 2, 207, 'content', 100157, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100209', 1, 2, 0, 2, 208, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100210', 1, 2, 0, 3, 209, 'content', 100158, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100211', 1, 2, 0, 3, 210, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100212', 1, 2, 0, 4, 211, 'content', 100159, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100213', 1, 2, 0, 4, 212, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100214', 1, 2, 0, 4, 213, 'content', 100160, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100215', 1, 2, 0, 4, 214, 'prompt', 100028, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100216', 1, 2, 0, 1, 215, 'content', 100161, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100217', 1, 2, 0, 1, 216, 'prompt', 100029, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100218', 1, 2, 0, 2, 217, 'content', 100162, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100219', 1, 2, 0, 2, 218, 'prompt', 100030, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100220', 1, 2, 0, 3, 219, 'content', 100163, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100221', 1, 2, 0, 3, 220, 'prompt', 100031, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100222', 1, 2, 0, 4, 221, 'content', 100164, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100223', 1, 2, 0, 4, 222, 'prompt', 100032, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100224', 1, 2, 0, 5, 223, 'content', 100165, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100225', 1, 2, 0, 5, 224, 'prompt', 100033, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100226', 1, 2, 0, 6, 225, 'content', 100166, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100227', 1, 2, 0, 6, 226, 'prompt', 100034, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100228', 1, 2, 0, 6, 227, 'content', 100167, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100229', 1, 2, 0, 6, 228, 'content', 100168, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100230', 1, 2, 0, 6, 229, 'content', 100169, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100231', 1, 2, 0, 6, 230, 'content', 100170, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100232', 1, 2, 0, 6, 231, 'content', 100171, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100233', 1, 2, 0, 6, 232, 'content', 100172, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100234', 1, 2, 0, 6, 233, 'content', 100173, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100235', 1, 2, 0, 6, 234, 'content', 100174, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100236', 1, 2, 0, 6, 235, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100237', 1, 2, 0, 6, 236, 'content', 100175, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100238', 1, 2, 0, 6, 237, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100239', 1, 2, 0, 6, 238, 'content', 100176, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100240', 1, 2, 0, 6, 239, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100241', 1, 2, 0, 6, 240, 'content', 100177, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100242', 1, 2, 0, 6, 241, 'prompt', 100035, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100243', 1, 2, 0, 6, 242, 'content', 100178, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100244', 1, 2, 0, 6, 243, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100245', 1, 2, 0, 6, 244, 'content', 100179, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100246', 1, 2, 0, 6, 245, 'prompt', 100036, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100247', 1, 2, 0, 6, 246, 'content', 100180, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100248', 1, 2, 0, 6, 247, 'prompt', 100037, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100249', 1, 2, 0, 6, 248, 'content', 100181, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100250', 1, 2, 0, 6, 249, 'prompt', 100038, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100251', 1, 2, 0, 6, 250, 'content', 100182, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100252', 1, 2, 0, 6, 251, 'prompt', 100039, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100253', 1, 2, 0, 6, 252, 'content', 100183, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100254', 1, 2, 0, 6, 253, 'content', 100184, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100255', 1, 2, 0, 6, 254, 'content', 100185, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100256', 1, 2, 0, 6, 255, 'content', 100186, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100257', 1, 2, 0, 6, 256, 'content', 100187, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100258', 1, 2, 0, 6, 257, 'content', 100188, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100259', 1, 2, 0, 6, 258, 'content', 100189, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100260', 1, 2, 0, 6, 259, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100261', 1, 2, 0, 6, 260, 'content', 100190, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100262', 1, 2, 0, 6, 261, 'tool', 100005, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100263', 1, 2, 0, 6, 262, 'content', 100191, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100264', 1, 2, 0, 6, 263, 'content', 100192, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100265', 1, 2, 0, 6, 264, 'tool', 100000, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100266', 1, 2, 0, 6, 265, 'content', 100193, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100267', 1, 2, 0, 6, 266, 'content', 100194, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100268', 1, 2, 0, 6, 267, 'prompt', 100040, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100269', 1, 2, 0, 6, 268, 'content', 100195, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100270', 1, 2, 0, 6, 269, 'prompt', 100041, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100271', 1, 2, 0, 6, 270, 'content', 100196, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100272', 1, 2, 0, 6, 271, 'prompt', 100042, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100273', 1, 2, 0, 6, 272, 'content', 100197, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100274', 1, 2, 0, 6, 273, 'prompt', 100043, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100275', 1, 2, 0, 6, 274, 'content', 100198, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100276', 1, 2, 0, 6, 275, 'prompt', 100044, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100277', 1, 3, 0, 0, 276, 'content', 100199, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100278', 1, 3, 0, 0, 277, 'content', 100200, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100279', 1, 3, 0, 0, 278, 'content', 100201, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100280', 1, 3, 0, 0, 279, 'content', 100202, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100281', 1, 3, 0, 0, 280, 'content', 100203, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100282', 1, 3, 0, 0, 281, 'content', 100204, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100283', 1, 3, 0, 0, 282, 'content', 100205, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100284', 1, 3, 0, 0, 283, 'content', 100206, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100285', 1, 3, 0, 0, 284, 'content', 100207, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100286', 1, 3, 0, 0, 285, 'tool', 100003, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100287', 1, 3, 0, 0, 286, 'content', 100208, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100288', 1, 3, 0, 0, 287, 'prompt', 100045, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100289', 1, 3, 0, 0, 288, 'content', 100209, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100290', 1, 3, 0, 0, 289, 'content', 100210, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100291', 1, 3, 0, 0, 290, 'content', 100211, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100292', 1, 3, 0, 0, 291, 'content', 100212, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100293', 1, 3, 0, 0, 292, 'content', 100213, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100294', 1, 3, 0, 0, 293, 'content', 100214, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100295', 1, 3, 0, 0, 294, 'content', 100215, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100296', 1, 3, 0, 0, 295, 'content', 100216, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100297', 1, 3, 0, 0, 296, 'content', 100217, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100298', 1, 3, 0, 0, 297, 'content', 100218, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100299', 1, 3, 0, 0, 298, 'content', 100219, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100300', 1, 3, 0, 0, 299, 'content', 100220, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100301', 1, 3, 0, 0, 300, 'content', 100221, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100302', 1, 3, 0, 0, 301, 'content', 100222, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100303', 1, 3, 0, 0, 302, 'content', 100223, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100304', 1, 3, 0, 0, 303, 'content', 100224, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100305', 1, 3, 0, 0, 304, 'content', 100225, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100306', 1, 3, 0, 0, 305, 'content', 100226, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100307', 1, 3, 0, 0, 306, 'tool', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100308', 1, 3, 0, 0, 307, 'content', 100227, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100309', 1, 3, 0, 0, 308, 'tool', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100310', 1, 3, 0, 0, 309, 'content', 100228, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100311', 1, 3, 0, 0, 310, 'tool', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100312', 1, 3, 0, 0, 311, 'content', 100229, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100313', 1, 3, 0, 0, 312, 'prompt', 100046, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100314', 1, 3, 0, 0, 313, 'content', 100230, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100315', 1, 3, 0, 0, 314, 'content', 100231, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100316', 1, 3, 0, 0, 315, 'content', 100232, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100317', 1, 3, 0, 0, 316, 'tool', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100318', 1, 3, 0, 0, 317, 'content', 100233, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100319', 1, 3, 0, 0, 318, 'prompt', 100047, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100320', 1, 3, 0, 0, 319, 'content', 100234, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100321', 1, 3, 0, 0, 320, 'tool', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100322', 1, 3, 0, 0, 321, 'content', 100235, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100323', 1, 3, 0, 0, 322, 'prompt', 100048, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100324', 1, 3, 0, 0, 323, 'content', 100236, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100325', 1, 3, 0, 0, 324, 'content', 100237, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100326', 1, 3, 0, 0, 325, 'content', 100238, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100327', 1, 3, 0, 0, 326, 'tool', 100006, NULL);
INSERT INTO stem (id, part, module, exercise, activity, sequence, block_type, content_id, connection_id) VALUES ('100328', 1, 3, 0, 0, 327, 'content', 100239, NULL);
