// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dreamtree/reputation/v1/types.proto

package reputation

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RateBucket — the decay class a contribution decays at (read-time projection).
type RateBucket int32

const (
	RateBucket_RATE_BUCKET_UNSPECIFIED RateBucket = 0
	RateBucket_RATE_BUCKET_PERMANENT   RateBucket = 1
	RateBucket_RATE_BUCKET_DURABLE_25Y RateBucket = 2
	RateBucket_RATE_BUCKET_RIGOR       RateBucket = 3
	RateBucket_RATE_BUCKET_USE         RateBucket = 4
	RateBucket_RATE_BUCKET_REPLICATION RateBucket = 5
	RateBucket_RATE_BUCKET_ENDORSEMENT RateBucket = 6
)

var RateBucket_name = map[int32]string{
	0: "RATE_BUCKET_UNSPECIFIED",
	1: "RATE_BUCKET_PERMANENT",
	2: "RATE_BUCKET_DURABLE_25Y",
	3: "RATE_BUCKET_RIGOR",
	4: "RATE_BUCKET_USE",
	5: "RATE_BUCKET_REPLICATION",
	6: "RATE_BUCKET_ENDORSEMENT",
}

var RateBucket_value = map[string]int32{
	"RATE_BUCKET_UNSPECIFIED": 0,
	"RATE_BUCKET_PERMANENT":   1,
	"RATE_BUCKET_DURABLE_25Y": 2,
	"RATE_BUCKET_RIGOR":       3,
	"RATE_BUCKET_USE":         4,
	"RATE_BUCKET_REPLICATION": 5,
	"RATE_BUCKET_ENDORSEMENT": 6,
}

func (x RateBucket) String() string {
	return proto.EnumName(RateBucket_name, int32(x))
}

func (RateBucket) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{0}
}

// PendingKind — what a pending event settles into.
type PendingKind int32

const (
	PendingKind_PENDING_KIND_UNSPECIFIED PendingKind = 0
	PendingKind_PENDING_KIND_BET         PendingKind = 1
	PendingKind_PENDING_KIND_OUTCOME     PendingKind = 2
)

var PendingKind_name = map[int32]string{
	0: "PENDING_KIND_UNSPECIFIED",
	1: "PENDING_KIND_BET",
	2: "PENDING_KIND_OUTCOME",
}

var PendingKind_value = map[string]int32{
	"PENDING_KIND_UNSPECIFIED": 0,
	"PENDING_KIND_BET":         1,
	"PENDING_KIND_OUTCOME":     2,
}

func (x PendingKind) String() string {
	return proto.EnumName(PendingKind_name, int32(x))
}

func (PendingKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{1}
}

// Contribution — an immutable, settled increment to a signer's reputation in a
// domain. This is the ONLY reputation state stored. R(j,k,t) is a projection
// over these (baseline + Σ magnitude·relevance·decay), computed at read time.
// magnitude is fixed-point (LegacyDec) because settlement is consensus math;
// the exponential decay applied to it is float, read-side only.
type Contribution struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// signer — whose reputation this moves (j).
	Signer string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	// domain — the 5-level taxonomy path (k).
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// magnitude — signed fixed-point increment (may be negative for reversals).
	Magnitude  cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=magnitude,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"magnitude"`
	RateBucket RateBucket                  `protobuf:"varint,5,opt,name=rate_bucket,json=rateBucket,proto3,enum=dreamtree.reputation.v1.RateBucket" json:"rate_bucket,omitempty"`
	// settled_at — block time (unix) the contribution took effect; decay clock start.
	SettledAt int64 `protobuf:"varint,6,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	// source_att_id — the attestation/outcome that produced it (provenance; 0 = none).
	SourceAttId uint64 `protobuf:"varint,7,opt,name=source_att_id,json=sourceAttId,proto3" json:"source_att_id,omitempty"`
	Height      int64  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Contribution) Reset()         { *m = Contribution{} }
func (m *Contribution) String() string { return proto.CompactTextString(m) }
func (*Contribution) ProtoMessage()    {}
func (*Contribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{0}
}
func (m *Contribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contribution.Merge(m, src)
}
func (m *Contribution) XXX_Size() int {
	return m.Size()
}
func (m *Contribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Contribution.DiscardUnknown(m)
}

var xxx_messageInfo_Contribution proto.InternalMessageInfo

func (m *Contribution) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contribution) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *Contribution) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Contribution) GetRateBucket() RateBucket {
	if m != nil {
		return m.RateBucket
	}
	return RateBucket_RATE_BUCKET_UNSPECIFIED
}

func (m *Contribution) GetSettledAt() int64 {
	if m != nil {
		return m.SettledAt
	}
	return 0
}

func (m *Contribution) GetSourceAttId() uint64 {
	if m != nil {
		return m.SourceAttId
	}
	return 0
}

func (m *Contribution) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// DomainConfig — per-domain governance tiers (saturation + obsolescence).
// Absent domains use the standard defaults.
type DomainConfig struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// saturation_point S — log-dampening threshold (small 5 / standard 10 / large 50).
	SaturationPoint cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=saturation_point,json=saturationPoint,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"saturation_point"`
	// obsolescence_multiplier — scales decay (foundational .3 / standard 1 / frontier 3).
	ObsolescenceMultiplier cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=obsolescence_multiplier,json=obsolescenceMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"obsolescence_multiplier"`
}

func (m *DomainConfig) Reset()         { *m = DomainConfig{} }
func (m *DomainConfig) String() string { return proto.CompactTextString(m) }
func (*DomainConfig) ProtoMessage()    {}
func (*DomainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{1}
}
func (m *DomainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainConfig.Merge(m, src)
}
func (m *DomainConfig) XXX_Size() int {
	return m.Size()
}
func (m *DomainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DomainConfig proto.InternalMessageInfo

func (m *DomainConfig) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Params — the reputation levers (parameters.md). Decimal strings are read-side
// (decay/saturation) inputs; kept as strings, parsed in the projection.
type Params struct {
	BaselineKyc          string `protobuf:"bytes,1,opt,name=baseline_kyc,json=baselineKyc,proto3" json:"baseline_kyc,omitempty"`
	DampeningK           string `protobuf:"bytes,2,opt,name=dampening_k,json=dampeningK,proto3" json:"dampening_k,omitempty"`
	SaturationStandard   string `protobuf:"bytes,3,opt,name=saturation_standard,json=saturationStandard,proto3" json:"saturation_standard,omitempty"`
	ObsolescenceStandard string `protobuf:"bytes,4,opt,name=obsolescence_standard,json=obsolescenceStandard,proto3" json:"obsolescence_standard,omitempty"`
	// per-bucket decay λ (per year); origin/permanent = 0
	LambdaPermanent   string `protobuf:"bytes,5,opt,name=lambda_permanent,json=lambdaPermanent,proto3" json:"lambda_permanent,omitempty"`
	LambdaDurable     string `protobuf:"bytes,6,opt,name=lambda_durable,json=lambdaDurable,proto3" json:"lambda_durable,omitempty"`
	LambdaRigor       string `protobuf:"bytes,7,opt,name=lambda_rigor,json=lambdaRigor,proto3" json:"lambda_rigor,omitempty"`
	LambdaUse         string `protobuf:"bytes,8,opt,name=lambda_use,json=lambdaUse,proto3" json:"lambda_use,omitempty"`
	LambdaReplication string `protobuf:"bytes,9,opt,name=lambda_replication,json=lambdaReplication,proto3" json:"lambda_replication,omitempty"`
	LambdaEndorsement string `protobuf:"bytes,10,opt,name=lambda_endorsement,json=lambdaEndorsement,proto3" json:"lambda_endorsement,omitempty"`
	// P1 unvalidated-bet magnitude: an attestation contributes this × (spec × type_weight).
	AttestBetScale string `protobuf:"bytes,11,opt,name=attest_bet_scale,json=attestBetScale,proto3" json:"attest_bet_scale,omitempty"`
	// P2/P3 review-window + outcome levers (parameters.md).
	NegAsymmetry          string `protobuf:"bytes,12,opt,name=neg_asymmetry,json=negAsymmetry,proto3" json:"neg_asymmetry,omitempty"`
	OutcomeBeta           string `protobuf:"bytes,13,opt,name=outcome_beta,json=outcomeBeta,proto3" json:"outcome_beta,omitempty"`
	OutcomeCapMult        string `protobuf:"bytes,14,opt,name=outcome_cap_mult,json=outcomeCapMult,proto3" json:"outcome_cap_mult,omitempty"`
	ReviewWindowBase      string `protobuf:"bytes,15,opt,name=review_window_base,json=reviewWindowBase,proto3" json:"review_window_base,omitempty"`
	ReviewWindowThreshold string `protobuf:"bytes,16,opt,name=review_window_threshold,json=reviewWindowThreshold,proto3" json:"review_window_threshold,omitempty"`
	// co-attestor propagation: another attestor on the same work moves this × M_O.
	CoattestorWeight string `protobuf:"bytes,17,opt,name=coattestor_weight,json=coattestorWeight,proto3" json:"coattestor_weight,omitempty"`
	// endorsement inheritance: B inherits this × endorser's standing (geometric
	// multi-hop decay + 2-hop cred recursion fall out of standing including
	// endorsement contributions).
	EndorseInherit string `protobuf:"bytes,18,opt,name=endorse_inherit,json=endorseInherit,proto3" json:"endorse_inherit,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBaselineKyc() string {
	if m != nil {
		return m.BaselineKyc
	}
	return ""
}

func (m *Params) GetDampeningK() string {
	if m != nil {
		return m.DampeningK
	}
	return ""
}

func (m *Params) GetSaturationStandard() string {
	if m != nil {
		return m.SaturationStandard
	}
	return ""
}

func (m *Params) GetObsolescenceStandard() string {
	if m != nil {
		return m.ObsolescenceStandard
	}
	return ""
}

func (m *Params) GetLambdaPermanent() string {
	if m != nil {
		return m.LambdaPermanent
	}
	return ""
}

func (m *Params) GetLambdaDurable() string {
	if m != nil {
		return m.LambdaDurable
	}
	return ""
}

func (m *Params) GetLambdaRigor() string {
	if m != nil {
		return m.LambdaRigor
	}
	return ""
}

func (m *Params) GetLambdaUse() string {
	if m != nil {
		return m.LambdaUse
	}
	return ""
}

func (m *Params) GetLambdaReplication() string {
	if m != nil {
		return m.LambdaReplication
	}
	return ""
}

func (m *Params) GetLambdaEndorsement() string {
	if m != nil {
		return m.LambdaEndorsement
	}
	return ""
}

func (m *Params) GetAttestBetScale() string {
	if m != nil {
		return m.AttestBetScale
	}
	return ""
}

func (m *Params) GetNegAsymmetry() string {
	if m != nil {
		return m.NegAsymmetry
	}
	return ""
}

func (m *Params) GetOutcomeBeta() string {
	if m != nil {
		return m.OutcomeBeta
	}
	return ""
}

func (m *Params) GetOutcomeCapMult() string {
	if m != nil {
		return m.OutcomeCapMult
	}
	return ""
}

func (m *Params) GetReviewWindowBase() string {
	if m != nil {
		return m.ReviewWindowBase
	}
	return ""
}

func (m *Params) GetReviewWindowThreshold() string {
	if m != nil {
		return m.ReviewWindowThreshold
	}
	return ""
}

func (m *Params) GetCoattestorWeight() string {
	if m != nil {
		return m.CoattestorWeight
	}
	return ""
}

func (m *Params) GetEndorseInherit() string {
	if m != nil {
		return m.EndorseInherit
	}
	return ""
}

// PendingEvent — a reputation-moving event inside its review window. At
// close_time, EndBlock integrates its accumulators and settles it into
// Contribution(s). Nothing here moves R until settled.
type PendingEvent struct {
	Id   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind PendingKind `protobuf:"varint,2,opt,name=kind,proto3,enum=dreamtree.reputation.v1.PendingKind" json:"kind,omitempty"`
	// BET fields (kind = BET): whose R, and the bet magnitude/bucket.
	Signer     string     `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	Domain     string     `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	RateBucket RateBucket `protobuf:"varint,5,opt,name=rate_bucket,json=rateBucket,proto3,enum=dreamtree.reputation.v1.RateBucket" json:"rate_bucket,omitempty"`
	// OUTCOME fields (kind = OUTCOME): the contested claim on target_att.
	TargetAttId          uint64                      `protobuf:"varint,6,opt,name=target_att_id,json=targetAttId,proto3" json:"target_att_id,omitempty"`
	TargetAttestor       string                      `protobuf:"bytes,7,opt,name=target_attestor,json=targetAttestor,proto3" json:"target_attestor,omitempty"`
	TargetDomain         string                      `protobuf:"bytes,8,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	TargetSIssuance      cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=target_s_issuance,json=targetSIssuance,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"target_s_issuance"`
	OutcomeRefutes       bool                        `protobuf:"varint,10,opt,name=outcome_refutes,json=outcomeRefutes,proto3" json:"outcome_refutes,omitempty"`
	CounterTargetPending uint64                      `protobuf:"varint,11,opt,name=counter_target_pending,json=counterTargetPending,proto3" json:"counter_target_pending,omitempty"`
	// base_magnitude — the event's own magnitude before window integration
	// (the bet, or the reporter's initial M_O contribution).
	BaseMagnitude cosmossdk_io_math.LegacyDec `protobuf:"bytes,12,opt,name=base_magnitude,json=baseMagnitude,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"base_magnitude"`
	// accumulators — corroboration/refutation gathered during the window (paper-shape).
	Corroboration cosmossdk_io_math.LegacyDec `protobuf:"bytes,13,opt,name=corroboration,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"corroboration"`
	Refutation    cosmossdk_io_math.LegacyDec `protobuf:"bytes,14,opt,name=refutation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"refutation"`
	OpenedAt      int64                       `protobuf:"varint,15,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	CloseTime     int64                       `protobuf:"varint,16,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	SourceAttId   uint64                      `protobuf:"varint,17,opt,name=source_att_id,json=sourceAttId,proto3" json:"source_att_id,omitempty"`
}

func (m *PendingEvent) Reset()         { *m = PendingEvent{} }
func (m *PendingEvent) String() string { return proto.CompactTextString(m) }
func (*PendingEvent) ProtoMessage()    {}
func (*PendingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{3}
}
func (m *PendingEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingEvent.Merge(m, src)
}
func (m *PendingEvent) XXX_Size() int {
	return m.Size()
}
func (m *PendingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PendingEvent proto.InternalMessageInfo

func (m *PendingEvent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PendingEvent) GetKind() PendingKind {
	if m != nil {
		return m.Kind
	}
	return PendingKind_PENDING_KIND_UNSPECIFIED
}

func (m *PendingEvent) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *PendingEvent) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *PendingEvent) GetRateBucket() RateBucket {
	if m != nil {
		return m.RateBucket
	}
	return RateBucket_RATE_BUCKET_UNSPECIFIED
}

func (m *PendingEvent) GetTargetAttId() uint64 {
	if m != nil {
		return m.TargetAttId
	}
	return 0
}

func (m *PendingEvent) GetTargetAttestor() string {
	if m != nil {
		return m.TargetAttestor
	}
	return ""
}

func (m *PendingEvent) GetTargetDomain() string {
	if m != nil {
		return m.TargetDomain
	}
	return ""
}

func (m *PendingEvent) GetOutcomeRefutes() bool {
	if m != nil {
		return m.OutcomeRefutes
	}
	return false
}

func (m *PendingEvent) GetCounterTargetPending() uint64 {
	if m != nil {
		return m.CounterTargetPending
	}
	return 0
}

func (m *PendingEvent) GetOpenedAt() int64 {
	if m != nil {
		return m.OpenedAt
	}
	return 0
}

func (m *PendingEvent) GetCloseTime() int64 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

func (m *PendingEvent) GetSourceAttId() uint64 {
	if m != nil {
		return m.SourceAttId
	}
	return 0
}

type GenesisState struct {
	Params        Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Contributions []Contribution `protobuf:"bytes,2,rep,name=contributions,proto3" json:"contributions"`
	DomainConfigs []DomainConfig `protobuf:"bytes,3,rep,name=domain_configs,json=domainConfigs,proto3" json:"domain_configs"`
	NextId        uint64         `protobuf:"varint,4,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
	PendingEvents []PendingEvent `protobuf:"bytes,5,rep,name=pending_events,json=pendingEvents,proto3" json:"pending_events"`
	NextPendingId uint64         `protobuf:"varint,6,opt,name=next_pending_id,json=nextPendingId,proto3" json:"next_pending_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetContributions() []Contribution {
	if m != nil {
		return m.Contributions
	}
	return nil
}

func (m *GenesisState) GetDomainConfigs() []DomainConfig {
	if m != nil {
		return m.DomainConfigs
	}
	return nil
}

func (m *GenesisState) GetNextId() uint64 {
	if m != nil {
		return m.NextId
	}
	return 0
}

func (m *GenesisState) GetPendingEvents() []PendingEvent {
	if m != nil {
		return m.PendingEvents
	}
	return nil
}

func (m *GenesisState) GetNextPendingId() uint64 {
	if m != nil {
		return m.NextPendingId
	}
	return 0
}

func init() {
	proto.RegisterEnum("dreamtree.reputation.v1.RateBucket", RateBucket_name, RateBucket_value)
	proto.RegisterEnum("dreamtree.reputation.v1.PendingKind", PendingKind_name, PendingKind_value)
	proto.RegisterType((*Contribution)(nil), "dreamtree.reputation.v1.Contribution")
	proto.RegisterType((*DomainConfig)(nil), "dreamtree.reputation.v1.DomainConfig")
	proto.RegisterType((*Params)(nil), "dreamtree.reputation.v1.Params")
	proto.RegisterType((*PendingEvent)(nil), "dreamtree.reputation.v1.PendingEvent")
	proto.RegisterType((*GenesisState)(nil), "dreamtree.reputation.v1.GenesisState")
}

func init() {
	proto.RegisterFile("dreamtree/reputation/v1/types.proto", fileDescriptor_9c263ffcf8ae5c16)
}

var fileDescriptor_9c263ffcf8ae5c16 = []byte{
	// 1412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4d, 0x73, 0xdb, 0x44,
	0x18, 0x8e, 0x63, 0xc7, 0xad, 0xd7, 0x9f, 0xd9, 0x26, 0x8d, 0xda, 0x42, 0x12, 0x52, 0x4a, 0x43,
	0x4a, 0x6c, 0x9a, 0x02, 0xc3, 0x70, 0xb3, 0x63, 0xd1, 0xf1, 0xa4, 0x71, 0x8c, 0xec, 0x10, 0x3e,
	0x47, 0xb3, 0x96, 0xde, 0xca, 0x4b, 0x2c, 0xad, 0x47, 0xbb, 0x4e, 0x9a, 0x3b, 0x27, 0x4e, 0xfc,
	0x01, 0xee, 0x3d, 0xf6, 0xd0, 0xff, 0x40, 0x8f, 0x9d, 0x9e, 0x18, 0x0e, 0x1d, 0xa6, 0x3d, 0xf4,
	0xc2, 0x4f, 0xe0, 0xc0, 0x68, 0x77, 0x6d, 0xcb, 0x29, 0xa1, 0x43, 0x86, 0x8b, 0x47, 0x7a, 0xde,
	0x67, 0x9f, 0xdd, 0xf7, 0xdd, 0xf7, 0x43, 0x46, 0xd7, 0xdd, 0x10, 0x88, 0x2f, 0x42, 0x80, 0x4a,
	0x08, 0x83, 0xa1, 0x20, 0x82, 0xb2, 0xa0, 0x72, 0x74, 0xbb, 0x22, 0x4e, 0x06, 0xc0, 0xcb, 0x83,
	0x90, 0x09, 0x86, 0x97, 0xc6, 0xa4, 0xf2, 0x84, 0x54, 0x3e, 0xba, 0x7d, 0x75, 0xc1, 0x63, 0x1e,
	0x93, 0x9c, 0x4a, 0xf4, 0xa4, 0xe8, 0x57, 0xe7, 0x89, 0x4f, 0x03, 0x56, 0x91, 0xbf, 0x1a, 0xba,
	0xe2, 0x30, 0xee, 0x33, 0x6e, 0x2b, 0xae, 0x7a, 0x51, 0xa6, 0xb5, 0x1f, 0x93, 0x28, 0xb7, 0xcd,
	0x02, 0x11, 0xd2, 0xee, 0x30, 0xd2, 0xc5, 0x05, 0x34, 0x4b, 0x5d, 0x23, 0xb1, 0x9a, 0x58, 0x4f,
	0x59, 0xb3, 0xd4, 0xc5, 0x1f, 0xa2, 0x34, 0xa7, 0x5e, 0x00, 0xa1, 0x31, 0xbb, 0x9a, 0x58, 0xcf,
	0xd4, 0x8c, 0x67, 0x8f, 0x37, 0x17, 0xb4, 0x44, 0xd5, 0x75, 0x43, 0xe0, 0xbc, 0x2d, 0x42, 0x1a,
	0x78, 0x96, 0xe6, 0xe1, 0xcb, 0x28, 0xed, 0x32, 0x9f, 0xd0, 0xc0, 0x48, 0x46, 0x2b, 0x2c, 0xfd,
	0x86, 0xf7, 0x50, 0xc6, 0x27, 0x5e, 0x40, 0xc5, 0xd0, 0x05, 0x23, 0x25, 0xc5, 0x6e, 0x3f, 0x79,
	0xbe, 0x32, 0xf3, 0xfb, 0xf3, 0x95, 0x6b, 0x4a, 0x90, 0xbb, 0x87, 0x65, 0xca, 0x2a, 0x3e, 0x11,
	0xbd, 0xf2, 0x3d, 0xf0, 0x88, 0x73, 0x52, 0x07, 0xe7, 0xd9, 0xe3, 0x4d, 0xa4, 0xf7, 0xab, 0x83,
	0x63, 0x4d, 0x34, 0x70, 0x1d, 0x65, 0x43, 0x22, 0xc0, 0xee, 0x0e, 0x9d, 0x43, 0x10, 0xc6, 0xdc,
	0x6a, 0x62, 0xbd, 0xb0, 0x75, 0xbd, 0x7c, 0x46, 0xb8, 0xca, 0x16, 0x11, 0x50, 0x93, 0x54, 0x0b,
	0x85, 0xe3, 0x67, 0xfc, 0x36, 0x42, 0x1c, 0x84, 0xe8, 0x83, 0x6b, 0x13, 0x61, 0xa4, 0x57, 0x13,
	0xeb, 0x49, 0x2b, 0xa3, 0x91, 0xaa, 0xc0, 0x6b, 0x28, 0xcf, 0xd9, 0x30, 0x74, 0xc0, 0x26, 0x42,
	0xd8, 0xd4, 0x35, 0x2e, 0xc8, 0xd0, 0x64, 0x15, 0x58, 0x15, 0xa2, 0xe1, 0x46, 0x1e, 0xf7, 0x80,
	0x7a, 0x3d, 0x61, 0x5c, 0x94, 0xcb, 0xf5, 0xdb, 0x67, 0xeb, 0x3f, 0xbd, 0x7a, 0xb4, 0x11, 0xbb,
	0xe3, 0x07, 0xf1, 0x5b, 0x8e, 0x47, 0x7d, 0xed, 0xcf, 0x04, 0xca, 0xd5, 0x65, 0x98, 0xb6, 0x59,
	0x70, 0x9f, 0x7a, 0x18, 0xa3, 0xd4, 0x80, 0x88, 0x9e, 0xbc, 0x88, 0x8c, 0x25, 0x9f, 0xf1, 0x77,
	0xa8, 0xc4, 0x89, 0x18, 0x86, 0x72, 0xbd, 0x3d, 0x60, 0x34, 0x10, 0xfa, 0x52, 0xce, 0x11, 0xc7,
	0xe2, 0x44, 0xaa, 0x15, 0x29, 0xe1, 0x1f, 0xd0, 0x12, 0xeb, 0x72, 0xd6, 0x07, 0xee, 0x40, 0xe0,
	0x80, 0xed, 0x0f, 0xfb, 0x82, 0x0e, 0xfa, 0x14, 0x42, 0x75, 0x8f, 0xe7, 0xd9, 0xe4, 0x72, 0x5c,
	0x71, 0x77, 0x2c, 0xb8, 0xf6, 0xd7, 0x1c, 0x4a, 0xb7, 0x48, 0x48, 0x7c, 0x8e, 0xdf, 0x41, 0xb9,
	0x2e, 0xe1, 0xd0, 0xa7, 0x01, 0xd8, 0x87, 0x27, 0x8e, 0x76, 0x38, 0x3b, 0xc2, 0x76, 0x4e, 0x1c,
	0xbc, 0x82, 0xb2, 0x2e, 0xf1, 0x07, 0x10, 0xd0, 0xc0, 0xb3, 0x0f, 0x95, 0xcb, 0x16, 0x1a, 0x43,
	0x3b, 0xb8, 0x82, 0x2e, 0xc5, 0x02, 0xc3, 0x05, 0x09, 0x5c, 0x12, 0xba, 0x3a, 0xfd, 0xf0, 0xc4,
	0xd4, 0xd6, 0x16, 0x7c, 0x07, 0x2d, 0x4e, 0xf9, 0x3a, 0x5e, 0x22, 0xd3, 0xd2, 0x5a, 0x88, 0x1b,
	0xc7, 0x8b, 0xde, 0x47, 0xa5, 0x3e, 0xf1, 0xbb, 0x2e, 0xb1, 0x07, 0x10, 0xfa, 0x24, 0x80, 0x40,
	0xe5, 0x5c, 0xc6, 0x2a, 0x2a, 0xbc, 0x35, 0x82, 0xf1, 0x0d, 0x54, 0xd0, 0x54, 0x77, 0x18, 0x92,
	0x6e, 0x1f, 0x64, 0x5e, 0x65, 0xac, 0xbc, 0x42, 0xeb, 0x0a, 0x8c, 0x7c, 0xd7, 0xb4, 0x90, 0x7a,
	0x2c, 0x94, 0xa9, 0x95, 0xb1, 0xb2, 0x0a, 0xb3, 0x22, 0x28, 0xca, 0x4e, 0x4d, 0x19, 0x72, 0x90,
	0xe9, 0x95, 0xb1, 0x32, 0x0a, 0xd9, 0xe7, 0x80, 0x37, 0x11, 0x1e, 0x29, 0xc0, 0xa0, 0x4f, 0x1d,
	0xe9, 0xa6, 0x91, 0x91, 0xb4, 0x79, 0xad, 0x33, 0x31, 0xc4, 0xe8, 0x10, 0xb8, 0x2c, 0xe4, 0xe0,
	0x47, 0x4e, 0xa0, 0x38, 0xdd, 0x9c, 0x18, 0xf0, 0x3a, 0x2a, 0x11, 0x21, 0x80, 0x0b, 0xbb, 0x0b,
	0xc2, 0xe6, 0x0e, 0xe9, 0x83, 0x91, 0x95, 0xe4, 0x82, 0xc2, 0x6b, 0x20, 0xda, 0x11, 0x8a, 0xaf,
	0xa3, 0x7c, 0x00, 0x9e, 0x4d, 0xf8, 0x89, 0xef, 0x83, 0x08, 0x4f, 0x8c, 0x9c, 0xa4, 0xe5, 0x02,
	0xf0, 0xaa, 0x23, 0x2c, 0x72, 0x97, 0x0d, 0x85, 0xc3, 0x7c, 0x88, 0xf4, 0x88, 0x91, 0x57, 0xee,
	0x6a, 0xac, 0x06, 0x82, 0x44, 0x3b, 0x8e, 0x28, 0x0e, 0x19, 0xc8, 0x1c, 0x34, 0x0a, 0x6a, 0x47,
	0x8d, 0x6f, 0x93, 0x41, 0x94, 0x48, 0xf8, 0x03, 0x84, 0x43, 0x38, 0xa2, 0x70, 0x6c, 0x1f, 0xd3,
	0xc0, 0x65, 0xc7, 0x76, 0x94, 0x31, 0x46, 0x51, 0x72, 0x4b, 0xca, 0x72, 0x20, 0x0d, 0x35, 0xc2,
	0x01, 0x7f, 0x82, 0x96, 0xa6, 0xd9, 0xa2, 0x17, 0x02, 0xef, 0xb1, 0xbe, 0x6b, 0x94, 0xe4, 0x92,
	0xc5, 0xf8, 0x92, 0xce, 0xc8, 0x88, 0x6f, 0xa1, 0x79, 0x87, 0x29, 0x5f, 0x59, 0x68, 0x1f, 0xab,
	0x22, 0x9f, 0x57, 0x9b, 0x4c, 0x0c, 0x07, 0x12, 0xc7, 0x37, 0x51, 0x51, 0x87, 0xd5, 0xa6, 0x41,
	0x0f, 0x42, 0x2a, 0x0c, 0xac, 0xce, 0xae, 0xe1, 0x86, 0x42, 0xd7, 0x1e, 0x5e, 0x40, 0xb9, 0x16,
	0x04, 0x2e, 0x0d, 0x3c, 0xf3, 0x28, 0x0a, 0xf4, 0xe9, 0xa6, 0xfb, 0x29, 0x4a, 0x1d, 0xd2, 0xc0,
	0x95, 0xa9, 0x5e, 0xd8, 0x7a, 0xf7, 0xcc, 0x96, 0xa6, 0x45, 0x76, 0x68, 0xe0, 0x5a, 0x72, 0x45,
	0xac, 0x5d, 0x27, 0xff, 0x73, 0xbb, 0x4e, 0x4d, 0xb5, 0xeb, 0xff, 0xa7, 0xbb, 0xae, 0xa1, 0xbc,
	0x20, 0xa1, 0x07, 0x62, 0xd4, 0x3e, 0xd3, 0xaa, 0x7d, 0x2a, 0x50, 0xb5, 0xcf, 0x9b, 0xa8, 0x38,
	0xe1, 0xc8, 0x80, 0xea, 0x4a, 0x28, 0x8c, 0x59, 0x12, 0x8d, 0xb2, 0x4c, 0x13, 0xf5, 0x89, 0x55,
	0x3d, 0xe4, 0x14, 0xa8, 0xfa, 0x27, 0xfe, 0x1e, 0xcd, 0x6b, 0x12, 0xb7, 0x29, 0xe7, 0x43, 0x12,
	0x38, 0xa0, 0x2a, 0xe2, 0x5c, 0x6d, 0x52, 0x69, 0xb5, 0x1b, 0x5a, 0x29, 0x3a, 0xec, 0x28, 0x43,
	0x43, 0xb8, 0x3f, 0x14, 0xc0, 0x65, 0xfd, 0x5c, 0x1c, 0x27, 0xa8, 0xa5, 0x50, 0xfc, 0x11, 0xba,
	0xec, 0xb0, 0x61, 0x20, 0x20, 0xb4, 0xf5, 0x79, 0x06, 0xea, 0xb6, 0x64, 0x09, 0xa5, 0xac, 0x05,
	0x6d, 0xed, 0x48, 0xa3, 0xbe, 0x49, 0xfc, 0x15, 0x2a, 0x44, 0x89, 0x6c, 0x4f, 0x26, 0x65, 0xee,
	0xbc, 0x47, 0xcf, 0x47, 0x42, 0xbb, 0xe3, 0x69, 0x79, 0x80, 0xf2, 0x0e, 0x0b, 0x43, 0xd6, 0x65,
	0xaa, 0x19, 0xaa, 0xf2, 0x3b, 0x97, 0xf0, 0x94, 0x0e, 0xfe, 0x02, 0x21, 0x19, 0x09, 0xa5, 0x5a,
	0x38, 0xaf, 0x6a, 0x4c, 0x04, 0x5f, 0x43, 0x19, 0x36, 0x80, 0x40, 0x8d, 0xe4, 0xa2, 0x9c, 0xa9,
	0x17, 0x15, 0x50, 0x95, 0x03, 0xdb, 0xe9, 0x33, 0x0e, 0xb6, 0xa0, 0x3e, 0xc8, 0xf2, 0x4d, 0x5a,
	0x19, 0x89, 0x74, 0xa8, 0x0f, 0xaf, 0x0f, 0xec, 0xf9, 0xd7, 0x06, 0xf6, 0xbf, 0x0f, 0xe6, 0x78,
	0x65, 0xae, 0xfd, 0x92, 0x44, 0xb9, 0xbb, 0x10, 0x00, 0xa7, 0xbc, 0x2d, 0x88, 0x00, 0x5c, 0x43,
	0xe9, 0x81, 0x9c, 0x5c, 0xb2, 0x5c, 0xb3, 0x5b, 0x2b, 0x67, 0x17, 0xa7, 0xa4, 0xd5, 0x32, 0x51,
	0x28, 0x1e, 0xbe, 0x7a, 0xb4, 0x91, 0xb0, 0xf4, 0x4a, 0xfc, 0x65, 0x74, 0x15, 0x93, 0xe9, 0xcf,
	0x8d, 0xd9, 0xd5, 0xe4, 0x7a, 0x76, 0xeb, 0xc6, 0x99, 0x52, 0xf1, 0x6f, 0x85, 0xb8, 0xe0, 0xb4,
	0x0c, 0x3e, 0x40, 0x05, 0x55, 0x18, 0xb6, 0x23, 0xbf, 0x22, 0xb8, 0x91, 0x7c, 0x83, 0x70, 0xfc,
	0x9b, 0x63, 0x4a, 0xd8, 0x8d, 0x19, 0x38, 0x5e, 0x42, 0x17, 0x02, 0x78, 0x20, 0xa3, 0x99, 0x92,
	0xd1, 0x4c, 0x47, 0xaf, 0x0d, 0x37, 0xda, 0x51, 0x67, 0xb5, 0x0d, 0x51, 0xbc, 0xb8, 0x31, 0xf7,
	0x86, 0x1d, 0xe3, 0xd1, 0x9d, 0xda, 0x71, 0x10, 0x33, 0x70, 0xfc, 0x1e, 0x2a, 0xca, 0x1d, 0x47,
	0xea, 0xe3, 0xce, 0x91, 0x8f, 0x60, 0x2d, 0xd2, 0x70, 0x37, 0x7e, 0x4d, 0x20, 0x34, 0x69, 0x3d,
	0xf8, 0x1a, 0x5a, 0xb2, 0xaa, 0x1d, 0xd3, 0xae, 0xed, 0x6f, 0xef, 0x98, 0x1d, 0x7b, 0xbf, 0xd9,
	0x6e, 0x99, 0xdb, 0x8d, 0xcf, 0x1b, 0x66, 0xbd, 0x34, 0x83, 0xaf, 0xa0, 0xc5, 0xb8, 0xb1, 0x65,
	0x5a, 0xbb, 0xd5, 0xa6, 0xd9, 0xec, 0x94, 0x12, 0xa7, 0xd7, 0xd5, 0xf7, 0xad, 0x6a, 0xed, 0x9e,
	0x69, 0x6f, 0x7d, 0xfc, 0x75, 0x69, 0x16, 0x2f, 0xa2, 0xf9, 0xb8, 0xd1, 0x6a, 0xdc, 0xdd, 0xb3,
	0x4a, 0x49, 0x7c, 0x09, 0x15, 0xa7, 0xf6, 0x6a, 0x9b, 0xa5, 0xd4, 0x69, 0x21, 0xcb, 0x6c, 0xdd,
	0x6b, 0x6c, 0x57, 0x3b, 0x8d, 0xbd, 0x66, 0x69, 0xee, 0xb4, 0xd1, 0x6c, 0xd6, 0xf7, 0xac, 0xb6,
	0xb9, 0x1b, 0x1d, 0x21, 0xbd, 0xf1, 0x2d, 0xca, 0xc6, 0xda, 0x39, 0x7e, 0x0b, 0x19, 0x2d, 0xb3,
	0x59, 0x6f, 0x34, 0xef, 0xda, 0x3b, 0x8d, 0x66, 0xfd, 0x94, 0x2b, 0x0b, 0xa8, 0x34, 0x65, 0xad,
	0x99, 0x91, 0x17, 0x06, 0x5a, 0x98, 0x42, 0xf7, 0xf6, 0x3b, 0xdb, 0x7b, 0xbb, 0x66, 0x69, 0xb6,
	0x66, 0x3e, 0x79, 0xb1, 0x9c, 0x78, 0xfa, 0x62, 0x39, 0xf1, 0xc7, 0x8b, 0xe5, 0xc4, 0xcf, 0x2f,
	0x97, 0x67, 0x9e, 0xbe, 0x5c, 0x9e, 0xf9, 0xed, 0xe5, 0xf2, 0xcc, 0x37, 0xb7, 0x3c, 0x2a, 0x7a,
	0xc3, 0x6e, 0xd9, 0x61, 0x7e, 0xa5, 0xdb, 0x67, 0x81, 0xb7, 0xe9, 0xc2, 0x51, 0xe5, 0x9f, 0x4b,
	0xa3, 0x9b, 0x96, 0x7f, 0x1a, 0xee, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x14, 0xad, 0x12, 0x99,
	0xb8, 0x0c, 0x00, 0x00,
}

func (m *Contribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x40
	}
	if m.SourceAttId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SourceAttId))
		i--
		dAtA[i] = 0x38
	}
	if m.SettledAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SettledAt))
		i--
		dAtA[i] = 0x30
	}
	if m.RateBucket != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RateBucket))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Magnitude.Size()
		i -= size
		if _, err := m.Magnitude.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DomainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ObsolescenceMultiplier.Size()
		i -= size
		if _, err := m.ObsolescenceMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.SaturationPoint.Size()
		i -= size
		if _, err := m.SaturationPoint.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EndorseInherit) > 0 {
		i -= len(m.EndorseInherit)
		copy(dAtA[i:], m.EndorseInherit)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.EndorseInherit)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.CoattestorWeight) > 0 {
		i -= len(m.CoattestorWeight)
		copy(dAtA[i:], m.CoattestorWeight)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CoattestorWeight)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.ReviewWindowThreshold) > 0 {
		i -= len(m.ReviewWindowThreshold)
		copy(dAtA[i:], m.ReviewWindowThreshold)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ReviewWindowThreshold)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.ReviewWindowBase) > 0 {
		i -= len(m.ReviewWindowBase)
		copy(dAtA[i:], m.ReviewWindowBase)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ReviewWindowBase)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.OutcomeCapMult) > 0 {
		i -= len(m.OutcomeCapMult)
		copy(dAtA[i:], m.OutcomeCapMult)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OutcomeCapMult)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.OutcomeBeta) > 0 {
		i -= len(m.OutcomeBeta)
		copy(dAtA[i:], m.OutcomeBeta)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OutcomeBeta)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.NegAsymmetry) > 0 {
		i -= len(m.NegAsymmetry)
		copy(dAtA[i:], m.NegAsymmetry)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.NegAsymmetry)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.AttestBetScale) > 0 {
		i -= len(m.AttestBetScale)
		copy(dAtA[i:], m.AttestBetScale)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AttestBetScale)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.LambdaEndorsement) > 0 {
		i -= len(m.LambdaEndorsement)
		copy(dAtA[i:], m.LambdaEndorsement)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaEndorsement)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LambdaReplication) > 0 {
		i -= len(m.LambdaReplication)
		copy(dAtA[i:], m.LambdaReplication)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaReplication)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.LambdaUse) > 0 {
		i -= len(m.LambdaUse)
		copy(dAtA[i:], m.LambdaUse)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaUse)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.LambdaRigor) > 0 {
		i -= len(m.LambdaRigor)
		copy(dAtA[i:], m.LambdaRigor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaRigor)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.LambdaDurable) > 0 {
		i -= len(m.LambdaDurable)
		copy(dAtA[i:], m.LambdaDurable)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaDurable)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LambdaPermanent) > 0 {
		i -= len(m.LambdaPermanent)
		copy(dAtA[i:], m.LambdaPermanent)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaPermanent)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ObsolescenceStandard) > 0 {
		i -= len(m.ObsolescenceStandard)
		copy(dAtA[i:], m.ObsolescenceStandard)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ObsolescenceStandard)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SaturationStandard) > 0 {
		i -= len(m.SaturationStandard)
		copy(dAtA[i:], m.SaturationStandard)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SaturationStandard)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DampeningK) > 0 {
		i -= len(m.DampeningK)
		copy(dAtA[i:], m.DampeningK)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DampeningK)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BaselineKyc) > 0 {
		i -= len(m.BaselineKyc)
		copy(dAtA[i:], m.BaselineKyc)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BaselineKyc)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SourceAttId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SourceAttId))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.CloseTime != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CloseTime))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.OpenedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.OpenedAt))
		i--
		dAtA[i] = 0x78
	}
	{
		size := m.Refutation.Size()
		i -= size
		if _, err := m.Refutation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x72
	{
		size := m.Corroboration.Size()
		i -= size
		if _, err := m.Corroboration.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size := m.BaseMagnitude.Size()
		i -= size
		if _, err := m.BaseMagnitude.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.CounterTargetPending != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CounterTargetPending))
		i--
		dAtA[i] = 0x58
	}
	if m.OutcomeRefutes {
		i--
		if m.OutcomeRefutes {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	{
		size := m.TargetSIssuance.Size()
		i -= size
		if _, err := m.TargetSIssuance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.TargetDomain) > 0 {
		i -= len(m.TargetDomain)
		copy(dAtA[i:], m.TargetDomain)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TargetDomain)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.TargetAttestor) > 0 {
		i -= len(m.TargetAttestor)
		copy(dAtA[i:], m.TargetAttestor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TargetAttestor)))
		i--
		dAtA[i] = 0x3a
	}
	if m.TargetAttId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TargetAttId))
		i--
		dAtA[i] = 0x30
	}
	if m.RateBucket != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RateBucket))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Kind != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextPendingId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NextPendingId))
		i--
		dAtA[i] = 0x30
	}
	if len(m.PendingEvents) > 0 {
		for iNdEx := len(m.PendingEvents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingEvents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.NextId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NextId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DomainConfigs) > 0 {
		for iNdEx := len(m.DomainConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DomainConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Contributions) > 0 {
		for iNdEx := len(m.Contributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Magnitude.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.RateBucket != 0 {
		n += 1 + sovTypes(uint64(m.RateBucket))
	}
	if m.SettledAt != 0 {
		n += 1 + sovTypes(uint64(m.SettledAt))
	}
	if m.SourceAttId != 0 {
		n += 1 + sovTypes(uint64(m.SourceAttId))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	return n
}

func (m *DomainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.SaturationPoint.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.ObsolescenceMultiplier.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BaselineKyc)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DampeningK)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SaturationStandard)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ObsolescenceStandard)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaPermanent)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaDurable)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaRigor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaUse)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaReplication)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaEndorsement)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.AttestBetScale)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.NegAsymmetry)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OutcomeBeta)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.OutcomeCapMult)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ReviewWindowBase)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ReviewWindowThreshold)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	l = len(m.CoattestorWeight)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	l = len(m.EndorseInherit)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *PendingEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	if m.Kind != 0 {
		n += 1 + sovTypes(uint64(m.Kind))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.RateBucket != 0 {
		n += 1 + sovTypes(uint64(m.RateBucket))
	}
	if m.TargetAttId != 0 {
		n += 1 + sovTypes(uint64(m.TargetAttId))
	}
	l = len(m.TargetAttestor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TargetDomain)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.TargetSIssuance.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.OutcomeRefutes {
		n += 2
	}
	if m.CounterTargetPending != 0 {
		n += 1 + sovTypes(uint64(m.CounterTargetPending))
	}
	l = m.BaseMagnitude.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.Corroboration.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.Refutation.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.OpenedAt != 0 {
		n += 1 + sovTypes(uint64(m.OpenedAt))
	}
	if m.CloseTime != 0 {
		n += 2 + sovTypes(uint64(m.CloseTime))
	}
	if m.SourceAttId != 0 {
		n += 2 + sovTypes(uint64(m.SourceAttId))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Contributions) > 0 {
		for _, e := range m.Contributions {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.DomainConfigs) > 0 {
		for _, e := range m.DomainConfigs {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.NextId != 0 {
		n += 1 + sovTypes(uint64(m.NextId))
	}
	if len(m.PendingEvents) > 0 {
		for _, e := range m.PendingEvents {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.NextPendingId != 0 {
		n += 1 + sovTypes(uint64(m.NextPendingId))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Magnitude", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Magnitude.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateBucket", wireType)
			}
			m.RateBucket = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateBucket |= RateBucket(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettledAt", wireType)
			}
			m.SettledAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettledAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceAttId", wireType)
			}
			m.SourceAttId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceAttId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DomainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SaturationPoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SaturationPoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObsolescenceMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObsolescenceMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaselineKyc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaselineKyc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DampeningK", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DampeningK = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SaturationStandard", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SaturationStandard = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObsolescenceStandard", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObsolescenceStandard = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaPermanent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaPermanent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaDurable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaDurable = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaRigor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaRigor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaUse", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaUse = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaReplication", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaReplication = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaEndorsement", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaEndorsement = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestBetScale", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestBetScale = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NegAsymmetry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NegAsymmetry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutcomeBeta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutcomeBeta = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutcomeCapMult", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutcomeCapMult = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewWindowBase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReviewWindowBase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReviewWindowThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReviewWindowThreshold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoattestorWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CoattestorWeight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndorseInherit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndorseInherit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= PendingKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateBucket", wireType)
			}
			m.RateBucket = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateBucket |= RateBucket(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAttId", wireType)
			}
			m.TargetAttId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetAttId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAttestor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetAttestor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetDomain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetDomain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetSIssuance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetSIssuance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutcomeRefutes", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OutcomeRefutes = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CounterTargetPending", wireType)
			}
			m.CounterTargetPending = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CounterTargetPending |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseMagnitude", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseMagnitude.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Corroboration", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Corroboration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refutation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Refutation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenedAt", wireType)
			}
			m.OpenedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpenedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloseTime", wireType)
			}
			m.CloseTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CloseTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceAttId", wireType)
			}
			m.SourceAttId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceAttId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributions = append(m.Contributions, Contribution{})
			if err := m.Contributions[len(m.Contributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DomainConfigs = append(m.DomainConfigs, DomainConfig{})
			if err := m.DomainConfigs[len(m.DomainConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextId", wireType)
			}
			m.NextId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingEvents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingEvents = append(m.PendingEvents, PendingEvent{})
			if err := m.PendingEvents[len(m.PendingEvents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPendingId", wireType)
			}
			m.NextPendingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPendingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
