// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dreamtree/reputation/v1/types.proto

package reputation

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RateBucket — the decay class a contribution decays at (read-time projection).
type RateBucket int32

const (
	RateBucket_RATE_BUCKET_UNSPECIFIED RateBucket = 0
	RateBucket_RATE_BUCKET_PERMANENT   RateBucket = 1
	RateBucket_RATE_BUCKET_DURABLE_25Y RateBucket = 2
	RateBucket_RATE_BUCKET_RIGOR       RateBucket = 3
	RateBucket_RATE_BUCKET_USE         RateBucket = 4
	RateBucket_RATE_BUCKET_REPLICATION RateBucket = 5
	RateBucket_RATE_BUCKET_ENDORSEMENT RateBucket = 6
)

var RateBucket_name = map[int32]string{
	0: "RATE_BUCKET_UNSPECIFIED",
	1: "RATE_BUCKET_PERMANENT",
	2: "RATE_BUCKET_DURABLE_25Y",
	3: "RATE_BUCKET_RIGOR",
	4: "RATE_BUCKET_USE",
	5: "RATE_BUCKET_REPLICATION",
	6: "RATE_BUCKET_ENDORSEMENT",
}

var RateBucket_value = map[string]int32{
	"RATE_BUCKET_UNSPECIFIED": 0,
	"RATE_BUCKET_PERMANENT":   1,
	"RATE_BUCKET_DURABLE_25Y": 2,
	"RATE_BUCKET_RIGOR":       3,
	"RATE_BUCKET_USE":         4,
	"RATE_BUCKET_REPLICATION": 5,
	"RATE_BUCKET_ENDORSEMENT": 6,
}

func (x RateBucket) String() string {
	return proto.EnumName(RateBucket_name, int32(x))
}

func (RateBucket) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{0}
}

// Contribution — an immutable, settled increment to a signer's reputation in a
// domain. This is the ONLY reputation state stored. R(j,k,t) is a projection
// over these (baseline + Σ magnitude·relevance·decay), computed at read time.
// magnitude is fixed-point (LegacyDec) because settlement is consensus math;
// the exponential decay applied to it is float, read-side only.
type Contribution struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// signer — whose reputation this moves (j).
	Signer string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	// domain — the 5-level taxonomy path (k).
	Domain string `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	// magnitude — signed fixed-point increment (may be negative for reversals).
	Magnitude  cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=magnitude,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"magnitude"`
	RateBucket RateBucket                  `protobuf:"varint,5,opt,name=rate_bucket,json=rateBucket,proto3,enum=dreamtree.reputation.v1.RateBucket" json:"rate_bucket,omitempty"`
	// settled_at — block time (unix) the contribution took effect; decay clock start.
	SettledAt int64 `protobuf:"varint,6,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	// source_att_id — the attestation/outcome that produced it (provenance; 0 = none).
	SourceAttId uint64 `protobuf:"varint,7,opt,name=source_att_id,json=sourceAttId,proto3" json:"source_att_id,omitempty"`
	Height      int64  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *Contribution) Reset()         { *m = Contribution{} }
func (m *Contribution) String() string { return proto.CompactTextString(m) }
func (*Contribution) ProtoMessage()    {}
func (*Contribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{0}
}
func (m *Contribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contribution.Merge(m, src)
}
func (m *Contribution) XXX_Size() int {
	return m.Size()
}
func (m *Contribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Contribution.DiscardUnknown(m)
}

var xxx_messageInfo_Contribution proto.InternalMessageInfo

func (m *Contribution) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contribution) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *Contribution) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Contribution) GetRateBucket() RateBucket {
	if m != nil {
		return m.RateBucket
	}
	return RateBucket_RATE_BUCKET_UNSPECIFIED
}

func (m *Contribution) GetSettledAt() int64 {
	if m != nil {
		return m.SettledAt
	}
	return 0
}

func (m *Contribution) GetSourceAttId() uint64 {
	if m != nil {
		return m.SourceAttId
	}
	return 0
}

func (m *Contribution) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// DomainConfig — per-domain governance tiers (saturation + obsolescence).
// Absent domains use the standard defaults.
type DomainConfig struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// saturation_point S — log-dampening threshold (small 5 / standard 10 / large 50).
	SaturationPoint cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=saturation_point,json=saturationPoint,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"saturation_point"`
	// obsolescence_multiplier — scales decay (foundational .3 / standard 1 / frontier 3).
	ObsolescenceMultiplier cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=obsolescence_multiplier,json=obsolescenceMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"obsolescence_multiplier"`
}

func (m *DomainConfig) Reset()         { *m = DomainConfig{} }
func (m *DomainConfig) String() string { return proto.CompactTextString(m) }
func (*DomainConfig) ProtoMessage()    {}
func (*DomainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{1}
}
func (m *DomainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainConfig.Merge(m, src)
}
func (m *DomainConfig) XXX_Size() int {
	return m.Size()
}
func (m *DomainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DomainConfig proto.InternalMessageInfo

func (m *DomainConfig) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Params — the reputation levers (parameters.md). Decimal strings are read-side
// (decay/saturation) inputs; kept as strings, parsed in the projection.
type Params struct {
	BaselineKyc          string `protobuf:"bytes,1,opt,name=baseline_kyc,json=baselineKyc,proto3" json:"baseline_kyc,omitempty"`
	DampeningK           string `protobuf:"bytes,2,opt,name=dampening_k,json=dampeningK,proto3" json:"dampening_k,omitempty"`
	SaturationStandard   string `protobuf:"bytes,3,opt,name=saturation_standard,json=saturationStandard,proto3" json:"saturation_standard,omitempty"`
	ObsolescenceStandard string `protobuf:"bytes,4,opt,name=obsolescence_standard,json=obsolescenceStandard,proto3" json:"obsolescence_standard,omitempty"`
	// per-bucket decay λ (per year); origin/permanent = 0
	LambdaPermanent   string `protobuf:"bytes,5,opt,name=lambda_permanent,json=lambdaPermanent,proto3" json:"lambda_permanent,omitempty"`
	LambdaDurable     string `protobuf:"bytes,6,opt,name=lambda_durable,json=lambdaDurable,proto3" json:"lambda_durable,omitempty"`
	LambdaRigor       string `protobuf:"bytes,7,opt,name=lambda_rigor,json=lambdaRigor,proto3" json:"lambda_rigor,omitempty"`
	LambdaUse         string `protobuf:"bytes,8,opt,name=lambda_use,json=lambdaUse,proto3" json:"lambda_use,omitempty"`
	LambdaReplication string `protobuf:"bytes,9,opt,name=lambda_replication,json=lambdaReplication,proto3" json:"lambda_replication,omitempty"`
	LambdaEndorsement string `protobuf:"bytes,10,opt,name=lambda_endorsement,json=lambdaEndorsement,proto3" json:"lambda_endorsement,omitempty"`
	// P1 unvalidated-bet magnitude: an attestation contributes this × (spec × type_weight).
	AttestBetScale string `protobuf:"bytes,11,opt,name=attest_bet_scale,json=attestBetScale,proto3" json:"attest_bet_scale,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBaselineKyc() string {
	if m != nil {
		return m.BaselineKyc
	}
	return ""
}

func (m *Params) GetDampeningK() string {
	if m != nil {
		return m.DampeningK
	}
	return ""
}

func (m *Params) GetSaturationStandard() string {
	if m != nil {
		return m.SaturationStandard
	}
	return ""
}

func (m *Params) GetObsolescenceStandard() string {
	if m != nil {
		return m.ObsolescenceStandard
	}
	return ""
}

func (m *Params) GetLambdaPermanent() string {
	if m != nil {
		return m.LambdaPermanent
	}
	return ""
}

func (m *Params) GetLambdaDurable() string {
	if m != nil {
		return m.LambdaDurable
	}
	return ""
}

func (m *Params) GetLambdaRigor() string {
	if m != nil {
		return m.LambdaRigor
	}
	return ""
}

func (m *Params) GetLambdaUse() string {
	if m != nil {
		return m.LambdaUse
	}
	return ""
}

func (m *Params) GetLambdaReplication() string {
	if m != nil {
		return m.LambdaReplication
	}
	return ""
}

func (m *Params) GetLambdaEndorsement() string {
	if m != nil {
		return m.LambdaEndorsement
	}
	return ""
}

func (m *Params) GetAttestBetScale() string {
	if m != nil {
		return m.AttestBetScale
	}
	return ""
}

type GenesisState struct {
	Params        Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Contributions []Contribution `protobuf:"bytes,2,rep,name=contributions,proto3" json:"contributions"`
	DomainConfigs []DomainConfig `protobuf:"bytes,3,rep,name=domain_configs,json=domainConfigs,proto3" json:"domain_configs"`
	NextId        uint64         `protobuf:"varint,4,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c263ffcf8ae5c16, []int{3}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetContributions() []Contribution {
	if m != nil {
		return m.Contributions
	}
	return nil
}

func (m *GenesisState) GetDomainConfigs() []DomainConfig {
	if m != nil {
		return m.DomainConfigs
	}
	return nil
}

func (m *GenesisState) GetNextId() uint64 {
	if m != nil {
		return m.NextId
	}
	return 0
}

func init() {
	proto.RegisterEnum("dreamtree.reputation.v1.RateBucket", RateBucket_name, RateBucket_value)
	proto.RegisterType((*Contribution)(nil), "dreamtree.reputation.v1.Contribution")
	proto.RegisterType((*DomainConfig)(nil), "dreamtree.reputation.v1.DomainConfig")
	proto.RegisterType((*Params)(nil), "dreamtree.reputation.v1.Params")
	proto.RegisterType((*GenesisState)(nil), "dreamtree.reputation.v1.GenesisState")
}

func init() {
	proto.RegisterFile("dreamtree/reputation/v1/types.proto", fileDescriptor_9c263ffcf8ae5c16)
}

var fileDescriptor_9c263ffcf8ae5c16 = []byte{
	// 936 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4d, 0x6f, 0xdb, 0x36,
	0x18, 0x8e, 0xec, 0xd4, 0x9d, 0xe8, 0x34, 0x71, 0xd8, 0xa4, 0x51, 0x5b, 0xcc, 0xc9, 0x52, 0x14,
	0xf0, 0x32, 0xc4, 0x5e, 0x52, 0xec, 0xb2, 0x9b, 0x1d, 0x6b, 0x85, 0x91, 0x2f, 0x83, 0x4e, 0x36,
	0x6c, 0x18, 0x20, 0xd0, 0xe2, 0x3b, 0x85, 0x8b, 0x45, 0x1a, 0x24, 0x15, 0x34, 0xf7, 0x9d, 0x76,
	0xda, 0x0f, 0xd8, 0x0f, 0xd8, 0xb1, 0x87, 0xfe, 0x87, 0xf5, 0x34, 0x14, 0x3d, 0x0d, 0x3b, 0x14,
	0x43, 0x72, 0xe8, 0x65, 0x3f, 0x62, 0x10, 0xa5, 0xd8, 0x4a, 0xb0, 0x60, 0x40, 0x2f, 0x06, 0xf9,
	0x3c, 0xcf, 0xfb, 0xd0, 0xef, 0x07, 0x29, 0xf4, 0x84, 0x29, 0xa0, 0xb1, 0x51, 0x00, 0x2d, 0x05,
	0xe3, 0xc4, 0x50, 0xc3, 0xa5, 0x68, 0x9d, 0x6d, 0xb5, 0xcc, 0xf9, 0x18, 0x74, 0x73, 0xac, 0xa4,
	0x91, 0x78, 0x65, 0x22, 0x6a, 0x4e, 0x45, 0xcd, 0xb3, 0xad, 0x47, 0x4b, 0x91, 0x8c, 0xa4, 0xd5,
	0xb4, 0xd2, 0x55, 0x26, 0x7f, 0xb4, 0x48, 0x63, 0x2e, 0x64, 0xcb, 0xfe, 0xe6, 0xd0, 0xc3, 0x50,
	0xea, 0x58, 0xea, 0x20, 0xd3, 0x66, 0x9b, 0x8c, 0x5a, 0xff, 0xa9, 0x8c, 0xe6, 0x76, 0xa4, 0x30,
	0x8a, 0x0f, 0x93, 0xd4, 0x17, 0xcf, 0xa3, 0x12, 0x67, 0x9e, 0xb3, 0xe6, 0x34, 0x66, 0x49, 0x89,
	0x33, 0xfc, 0x39, 0xaa, 0x68, 0x1e, 0x09, 0x50, 0x5e, 0x69, 0xcd, 0x69, 0xb8, 0x1d, 0xef, 0xed,
	0xab, 0xcd, 0xa5, 0xdc, 0xa2, 0xcd, 0x98, 0x02, 0xad, 0x07, 0x46, 0x71, 0x11, 0x91, 0x5c, 0x87,
	0x1f, 0xa0, 0x0a, 0x93, 0x31, 0xe5, 0xc2, 0x2b, 0xa7, 0x11, 0x24, 0xdf, 0xe1, 0x43, 0xe4, 0xc6,
	0x34, 0x12, 0xdc, 0x24, 0x0c, 0xbc, 0x59, 0x6b, 0xb6, 0xf5, 0xfa, 0xdd, 0xea, 0xcc, 0x5f, 0xef,
	0x56, 0x1f, 0x67, 0x86, 0x9a, 0x9d, 0x36, 0xb9, 0x6c, 0xc5, 0xd4, 0x9c, 0x34, 0xf7, 0x20, 0xa2,
	0xe1, 0x79, 0x17, 0xc2, 0xb7, 0xaf, 0x36, 0x51, 0x7e, 0x5e, 0x17, 0x42, 0x32, 0xf5, 0xc0, 0x5d,
	0x54, 0x55, 0xd4, 0x40, 0x30, 0x4c, 0xc2, 0x53, 0x30, 0xde, 0x9d, 0x35, 0xa7, 0x31, 0xbf, 0xfd,
	0xa4, 0x79, 0x4b, 0xb9, 0x9a, 0x84, 0x1a, 0xe8, 0x58, 0x29, 0x41, 0x6a, 0xb2, 0xc6, 0x1f, 0x23,
	0xa4, 0xc1, 0x98, 0x11, 0xb0, 0x80, 0x1a, 0xaf, 0xb2, 0xe6, 0x34, 0xca, 0xc4, 0xcd, 0x91, 0xb6,
	0xc1, 0xeb, 0xe8, 0x9e, 0x96, 0x89, 0x0a, 0x21, 0xa0, 0xc6, 0x04, 0x9c, 0x79, 0x77, 0x6d, 0x69,
	0xaa, 0x19, 0xd8, 0x36, 0xa6, 0xc7, 0xd2, 0x8c, 0x4f, 0x80, 0x47, 0x27, 0xc6, 0xfb, 0xc8, 0x86,
	0xe7, 0xbb, 0x2f, 0x1b, 0x3f, 0xbf, 0x7f, 0xb9, 0x51, 0xe8, 0xf1, 0x8b, 0x62, 0x97, 0x8b, 0x55,
	0x5f, 0xff, 0xc7, 0x41, 0x73, 0x5d, 0x5b, 0xa6, 0x1d, 0x29, 0x7e, 0xe0, 0x11, 0xc6, 0x68, 0x76,
	0x4c, 0xcd, 0x89, 0x6d, 0x84, 0x4b, 0xec, 0x1a, 0x7f, 0x8f, 0x6a, 0x9a, 0x9a, 0x44, 0xd9, 0xf8,
	0x60, 0x2c, 0xb9, 0x30, 0x79, 0x53, 0x3e, 0xa0, 0x8e, 0x0b, 0x53, 0xab, 0x7e, 0xea, 0x84, 0x7f,
	0x44, 0x2b, 0x72, 0xa8, 0xe5, 0x08, 0x74, 0x08, 0x22, 0x84, 0x20, 0x4e, 0x46, 0x86, 0x8f, 0x47,
	0x1c, 0x54, 0xd6, 0xc7, 0x0f, 0x39, 0xe4, 0x41, 0xd1, 0x71, 0x7f, 0x62, 0xb8, 0xfe, 0x47, 0x19,
	0x55, 0xfa, 0x54, 0xd1, 0x58, 0xe3, 0x4f, 0xd0, 0xdc, 0x90, 0x6a, 0x18, 0x71, 0x01, 0xc1, 0xe9,
	0x79, 0x98, 0x27, 0x5c, 0xbd, 0xc2, 0x76, 0xcf, 0x43, 0xbc, 0x8a, 0xaa, 0x8c, 0xc6, 0x63, 0x10,
	0x5c, 0x44, 0xc1, 0x69, 0x96, 0x32, 0x41, 0x13, 0x68, 0x17, 0xb7, 0xd0, 0xfd, 0x42, 0x61, 0xb4,
	0xa1, 0x82, 0x51, 0xc5, 0xf2, 0xf1, 0xc3, 0x53, 0x6a, 0x90, 0x33, 0xf8, 0x19, 0x5a, 0xbe, 0x96,
	0xeb, 0x24, 0xc4, 0x8e, 0x25, 0x59, 0x2a, 0x92, 0x93, 0xa0, 0x4f, 0x51, 0x6d, 0x44, 0xe3, 0x21,
	0xa3, 0xc1, 0x18, 0x54, 0x4c, 0x05, 0x88, 0x6c, 0xe6, 0x5c, 0xb2, 0x90, 0xe1, 0xfd, 0x2b, 0x18,
	0x3f, 0x45, 0xf3, 0xb9, 0x94, 0x25, 0x8a, 0x0e, 0x47, 0x60, 0xe7, 0xca, 0x25, 0xf7, 0x32, 0xb4,
	0x9b, 0x81, 0x69, 0xee, 0xb9, 0x4c, 0xf1, 0x48, 0x2a, 0x3b, 0x5a, 0x2e, 0xa9, 0x66, 0x18, 0x49,
	0xa1, 0x74, 0x3a, 0x73, 0x49, 0xa2, 0xc1, 0x8e, 0x97, 0x4b, 0xdc, 0x0c, 0x39, 0xd6, 0x80, 0x37,
	0x11, 0xbe, 0x72, 0x80, 0xf1, 0x88, 0x87, 0x36, 0x4d, 0xcf, 0xb5, 0xb2, 0xc5, 0xdc, 0x67, 0x4a,
	0x14, 0xe4, 0x20, 0x98, 0x54, 0x1a, 0xe2, 0x34, 0x09, 0x54, 0x94, 0xfb, 0x53, 0x02, 0x37, 0x50,
	0x8d, 0x1a, 0x03, 0xda, 0x04, 0x43, 0x30, 0x81, 0x0e, 0xe9, 0x08, 0xbc, 0xaa, 0x15, 0xcf, 0x67,
	0x78, 0x07, 0xcc, 0x20, 0x45, 0xd7, 0x7f, 0x2d, 0xa1, 0xb9, 0xe7, 0x20, 0x40, 0x73, 0x3d, 0x30,
	0xd4, 0x00, 0xee, 0xa0, 0xca, 0xd8, 0x36, 0xd8, 0x36, 0xb4, 0xba, 0xbd, 0x7a, 0xeb, 0xb5, 0xcc,
	0xe6, 0xa0, 0xe3, 0xa6, 0xd3, 0xf5, 0xdb, 0xfb, 0x97, 0x1b, 0x0e, 0xc9, 0x23, 0xf1, 0xd7, 0xe8,
	0x5e, 0x58, 0xb8, 0x24, 0xda, 0x2b, 0xad, 0x95, 0x1b, 0xd5, 0xed, 0xa7, 0xb7, 0x5a, 0x15, 0xaf,
	0x54, 0xd1, 0xf0, 0xba, 0x0d, 0xfe, 0x06, 0xcd, 0x67, 0x4f, 0x52, 0x10, 0xda, 0xcb, 0xa6, 0xbd,
	0xf2, 0xff, 0x18, 0x17, 0xaf, 0xe6, 0x35, 0x63, 0x56, 0x20, 0x34, 0x5e, 0x41, 0x77, 0x05, 0xbc,
	0xb0, 0xaf, 0xc4, 0xac, 0x7d, 0x25, 0x2a, 0xe9, 0xb6, 0xc7, 0x36, 0x7e, 0x77, 0x10, 0x9a, 0x3e,
	0x3f, 0xf8, 0x31, 0x5a, 0x21, 0xed, 0x23, 0x3f, 0xe8, 0x1c, 0xef, 0xec, 0xfa, 0x47, 0xc1, 0xf1,
	0xc1, 0xa0, 0xef, 0xef, 0xf4, 0xbe, 0xea, 0xf9, 0xdd, 0xda, 0x0c, 0x7e, 0x88, 0x96, 0x8b, 0x64,
	0xdf, 0x27, 0xfb, 0xed, 0x03, 0xff, 0xe0, 0xa8, 0xe6, 0xdc, 0x8c, 0xeb, 0x1e, 0x93, 0x76, 0x67,
	0xcf, 0x0f, 0xb6, 0xbf, 0xf8, 0xb6, 0x56, 0xc2, 0xcb, 0x68, 0xb1, 0x48, 0x92, 0xde, 0xf3, 0x43,
	0x52, 0x2b, 0xe3, 0xfb, 0x68, 0xe1, 0xda, 0x59, 0x03, 0xbf, 0x36, 0x7b, 0xd3, 0x88, 0xf8, 0xfd,
	0xbd, 0xde, 0x4e, 0xfb, 0xa8, 0x77, 0x78, 0x50, 0xbb, 0x73, 0x93, 0xf4, 0x0f, 0xba, 0x87, 0x64,
	0xe0, 0xef, 0xa7, 0x7f, 0xa1, 0xd2, 0xf1, 0x5f, 0x5f, 0xd4, 0x9d, 0x37, 0x17, 0x75, 0xe7, 0xef,
	0x8b, 0xba, 0xf3, 0xcb, 0x65, 0x7d, 0xe6, 0xcd, 0x65, 0x7d, 0xe6, 0xcf, 0xcb, 0xfa, 0xcc, 0x77,
	0x9f, 0x45, 0xdc, 0x9c, 0x24, 0xc3, 0x66, 0x28, 0xe3, 0xd6, 0x70, 0x24, 0x45, 0xb4, 0xc9, 0xe0,
	0xac, 0xf5, 0xdf, 0x8f, 0xdf, 0xb0, 0x62, 0xbf, 0x3e, 0xcf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x6a, 0x80, 0xc1, 0xe1, 0x01, 0x07, 0x00, 0x00,
}

func (m *Contribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x40
	}
	if m.SourceAttId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SourceAttId))
		i--
		dAtA[i] = 0x38
	}
	if m.SettledAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SettledAt))
		i--
		dAtA[i] = 0x30
	}
	if m.RateBucket != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RateBucket))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Magnitude.Size()
		i -= size
		if _, err := m.Magnitude.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DomainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ObsolescenceMultiplier.Size()
		i -= size
		if _, err := m.ObsolescenceMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.SaturationPoint.Size()
		i -= size
		if _, err := m.SaturationPoint.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AttestBetScale) > 0 {
		i -= len(m.AttestBetScale)
		copy(dAtA[i:], m.AttestBetScale)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AttestBetScale)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.LambdaEndorsement) > 0 {
		i -= len(m.LambdaEndorsement)
		copy(dAtA[i:], m.LambdaEndorsement)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaEndorsement)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LambdaReplication) > 0 {
		i -= len(m.LambdaReplication)
		copy(dAtA[i:], m.LambdaReplication)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaReplication)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.LambdaUse) > 0 {
		i -= len(m.LambdaUse)
		copy(dAtA[i:], m.LambdaUse)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaUse)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.LambdaRigor) > 0 {
		i -= len(m.LambdaRigor)
		copy(dAtA[i:], m.LambdaRigor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaRigor)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.LambdaDurable) > 0 {
		i -= len(m.LambdaDurable)
		copy(dAtA[i:], m.LambdaDurable)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaDurable)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LambdaPermanent) > 0 {
		i -= len(m.LambdaPermanent)
		copy(dAtA[i:], m.LambdaPermanent)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.LambdaPermanent)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ObsolescenceStandard) > 0 {
		i -= len(m.ObsolescenceStandard)
		copy(dAtA[i:], m.ObsolescenceStandard)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ObsolescenceStandard)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SaturationStandard) > 0 {
		i -= len(m.SaturationStandard)
		copy(dAtA[i:], m.SaturationStandard)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SaturationStandard)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DampeningK) > 0 {
		i -= len(m.DampeningK)
		copy(dAtA[i:], m.DampeningK)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.DampeningK)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BaselineKyc) > 0 {
		i -= len(m.BaselineKyc)
		copy(dAtA[i:], m.BaselineKyc)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BaselineKyc)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NextId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DomainConfigs) > 0 {
		for iNdEx := len(m.DomainConfigs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DomainConfigs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Contributions) > 0 {
		for iNdEx := len(m.Contributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Magnitude.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.RateBucket != 0 {
		n += 1 + sovTypes(uint64(m.RateBucket))
	}
	if m.SettledAt != 0 {
		n += 1 + sovTypes(uint64(m.SettledAt))
	}
	if m.SourceAttId != 0 {
		n += 1 + sovTypes(uint64(m.SourceAttId))
	}
	if m.Height != 0 {
		n += 1 + sovTypes(uint64(m.Height))
	}
	return n
}

func (m *DomainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.SaturationPoint.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.ObsolescenceMultiplier.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BaselineKyc)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.DampeningK)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SaturationStandard)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ObsolescenceStandard)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaPermanent)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaDurable)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaRigor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaUse)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaReplication)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.LambdaEndorsement)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.AttestBetScale)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Contributions) > 0 {
		for _, e := range m.Contributions {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.DomainConfigs) > 0 {
		for _, e := range m.DomainConfigs {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.NextId != 0 {
		n += 1 + sovTypes(uint64(m.NextId))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Magnitude", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Magnitude.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateBucket", wireType)
			}
			m.RateBucket = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RateBucket |= RateBucket(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettledAt", wireType)
			}
			m.SettledAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettledAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceAttId", wireType)
			}
			m.SourceAttId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceAttId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DomainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SaturationPoint", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SaturationPoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObsolescenceMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObsolescenceMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaselineKyc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaselineKyc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DampeningK", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DampeningK = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SaturationStandard", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SaturationStandard = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObsolescenceStandard", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ObsolescenceStandard = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaPermanent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaPermanent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaDurable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaDurable = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaRigor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaRigor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaUse", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaUse = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaReplication", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaReplication = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LambdaEndorsement", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LambdaEndorsement = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestBetScale", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AttestBetScale = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributions = append(m.Contributions, Contribution{})
			if err := m.Contributions[len(m.Contributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainConfigs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DomainConfigs = append(m.DomainConfigs, DomainConfig{})
			if err := m.DomainConfigs[len(m.DomainConfigs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextId", wireType)
			}
			m.NextId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
