// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dreamtree/attest/v1/query.proto

package attest

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAttestationRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryAttestationRequest) Reset()         { *m = QueryAttestationRequest{} }
func (m *QueryAttestationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttestationRequest) ProtoMessage()    {}
func (*QueryAttestationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{0}
}
func (m *QueryAttestationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestationRequest.Merge(m, src)
}
func (m *QueryAttestationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestationRequest proto.InternalMessageInfo

func (m *QueryAttestationRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryAttestationResponse struct {
	Attestation Attestation `protobuf:"bytes,1,opt,name=attestation,proto3" json:"attestation"`
}

func (m *QueryAttestationResponse) Reset()         { *m = QueryAttestationResponse{} }
func (m *QueryAttestationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttestationResponse) ProtoMessage()    {}
func (*QueryAttestationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{1}
}
func (m *QueryAttestationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestationResponse.Merge(m, src)
}
func (m *QueryAttestationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestationResponse proto.InternalMessageInfo

func (m *QueryAttestationResponse) GetAttestation() Attestation {
	if m != nil {
		return m.Attestation
	}
	return Attestation{}
}

type QueryBySubjectRequest struct {
	Subject    string             `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBySubjectRequest) Reset()         { *m = QueryBySubjectRequest{} }
func (m *QueryBySubjectRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBySubjectRequest) ProtoMessage()    {}
func (*QueryBySubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{2}
}
func (m *QueryBySubjectRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBySubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBySubjectRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBySubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBySubjectRequest.Merge(m, src)
}
func (m *QueryBySubjectRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBySubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBySubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBySubjectRequest proto.InternalMessageInfo

func (m *QueryBySubjectRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *QueryBySubjectRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryBySubjectResponse struct {
	Attestations []Attestation       `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBySubjectResponse) Reset()         { *m = QueryBySubjectResponse{} }
func (m *QueryBySubjectResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBySubjectResponse) ProtoMessage()    {}
func (*QueryBySubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{3}
}
func (m *QueryBySubjectResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBySubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBySubjectResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBySubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBySubjectResponse.Merge(m, src)
}
func (m *QueryBySubjectResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBySubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBySubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBySubjectResponse proto.InternalMessageInfo

func (m *QueryBySubjectResponse) GetAttestations() []Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func (m *QueryBySubjectResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryByAttestorRequest struct {
	Attestor   string             `protobuf:"bytes,1,opt,name=attestor,proto3" json:"attestor,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryByAttestorRequest) Reset()         { *m = QueryByAttestorRequest{} }
func (m *QueryByAttestorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryByAttestorRequest) ProtoMessage()    {}
func (*QueryByAttestorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{4}
}
func (m *QueryByAttestorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryByAttestorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryByAttestorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryByAttestorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryByAttestorRequest.Merge(m, src)
}
func (m *QueryByAttestorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryByAttestorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryByAttestorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryByAttestorRequest proto.InternalMessageInfo

func (m *QueryByAttestorRequest) GetAttestor() string {
	if m != nil {
		return m.Attestor
	}
	return ""
}

func (m *QueryByAttestorRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryByAttestorResponse struct {
	Attestations []Attestation       `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryByAttestorResponse) Reset()         { *m = QueryByAttestorResponse{} }
func (m *QueryByAttestorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryByAttestorResponse) ProtoMessage()    {}
func (*QueryByAttestorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{5}
}
func (m *QueryByAttestorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryByAttestorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryByAttestorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryByAttestorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryByAttestorResponse.Merge(m, src)
}
func (m *QueryByAttestorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryByAttestorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryByAttestorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryByAttestorResponse proto.InternalMessageInfo

func (m *QueryByAttestorResponse) GetAttestations() []Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

func (m *QueryByAttestorResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryStrengthRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryStrengthRequest) Reset()         { *m = QueryStrengthRequest{} }
func (m *QueryStrengthRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStrengthRequest) ProtoMessage()    {}
func (*QueryStrengthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{6}
}
func (m *QueryStrengthRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStrengthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStrengthRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStrengthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStrengthRequest.Merge(m, src)
}
func (m *QueryStrengthRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStrengthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStrengthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStrengthRequest proto.InternalMessageInfo

func (m *QueryStrengthRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryStrengthResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// All decimal readings are returned as strings — they are projections, not
	// consensus values.
	Strength        string `protobuf:"bytes,2,opt,name=strength,proto3" json:"strength,omitempty"`
	Reputation      string `protobuf:"bytes,3,opt,name=reputation,proto3" json:"reputation,omitempty"`
	Specificity     string `protobuf:"bytes,4,opt,name=specificity,proto3" json:"specificity,omitempty"`
	TypeWeight      string `protobuf:"bytes,5,opt,name=type_weight,json=typeWeight,proto3" json:"type_weight,omitempty"`
	Decay           string `protobuf:"bytes,6,opt,name=decay,proto3" json:"decay,omitempty"`
	RefutedFraction string `protobuf:"bytes,7,opt,name=refuted_fraction,json=refutedFraction,proto3" json:"refuted_fraction,omitempty"`
	AgeSeconds      int64  `protobuf:"varint,8,opt,name=age_seconds,json=ageSeconds,proto3" json:"age_seconds,omitempty"`
}

func (m *QueryStrengthResponse) Reset()         { *m = QueryStrengthResponse{} }
func (m *QueryStrengthResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStrengthResponse) ProtoMessage()    {}
func (*QueryStrengthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{7}
}
func (m *QueryStrengthResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStrengthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStrengthResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStrengthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStrengthResponse.Merge(m, src)
}
func (m *QueryStrengthResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStrengthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStrengthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStrengthResponse proto.InternalMessageInfo

func (m *QueryStrengthResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueryStrengthResponse) GetStrength() string {
	if m != nil {
		return m.Strength
	}
	return ""
}

func (m *QueryStrengthResponse) GetReputation() string {
	if m != nil {
		return m.Reputation
	}
	return ""
}

func (m *QueryStrengthResponse) GetSpecificity() string {
	if m != nil {
		return m.Specificity
	}
	return ""
}

func (m *QueryStrengthResponse) GetTypeWeight() string {
	if m != nil {
		return m.TypeWeight
	}
	return ""
}

func (m *QueryStrengthResponse) GetDecay() string {
	if m != nil {
		return m.Decay
	}
	return ""
}

func (m *QueryStrengthResponse) GetRefutedFraction() string {
	if m != nil {
		return m.RefutedFraction
	}
	return ""
}

func (m *QueryStrengthResponse) GetAgeSeconds() int64 {
	if m != nil {
		return m.AgeSeconds
	}
	return 0
}

type QueryWorkValueRequest struct {
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (m *QueryWorkValueRequest) Reset()         { *m = QueryWorkValueRequest{} }
func (m *QueryWorkValueRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWorkValueRequest) ProtoMessage()    {}
func (*QueryWorkValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{8}
}
func (m *QueryWorkValueRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWorkValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWorkValueRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWorkValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkValueRequest.Merge(m, src)
}
func (m *QueryWorkValueRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWorkValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkValueRequest proto.InternalMessageInfo

func (m *QueryWorkValueRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type QueryWorkValueResponse struct {
	Subject          string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Value            string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AttestationCount uint32 `protobuf:"varint,3,opt,name=attestation_count,json=attestationCount,proto3" json:"attestation_count,omitempty"`
}

func (m *QueryWorkValueResponse) Reset()         { *m = QueryWorkValueResponse{} }
func (m *QueryWorkValueResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWorkValueResponse) ProtoMessage()    {}
func (*QueryWorkValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{9}
}
func (m *QueryWorkValueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWorkValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWorkValueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWorkValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkValueResponse.Merge(m, src)
}
func (m *QueryWorkValueResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWorkValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkValueResponse proto.InternalMessageInfo

func (m *QueryWorkValueResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *QueryWorkValueResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *QueryWorkValueResponse) GetAttestationCount() uint32 {
	if m != nil {
		return m.AttestationCount
	}
	return 0
}

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{10}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bc25296bbe6226, []int{11}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*QueryAttestationRequest)(nil), "dreamtree.attest.v1.QueryAttestationRequest")
	proto.RegisterType((*QueryAttestationResponse)(nil), "dreamtree.attest.v1.QueryAttestationResponse")
	proto.RegisterType((*QueryBySubjectRequest)(nil), "dreamtree.attest.v1.QueryBySubjectRequest")
	proto.RegisterType((*QueryBySubjectResponse)(nil), "dreamtree.attest.v1.QueryBySubjectResponse")
	proto.RegisterType((*QueryByAttestorRequest)(nil), "dreamtree.attest.v1.QueryByAttestorRequest")
	proto.RegisterType((*QueryByAttestorResponse)(nil), "dreamtree.attest.v1.QueryByAttestorResponse")
	proto.RegisterType((*QueryStrengthRequest)(nil), "dreamtree.attest.v1.QueryStrengthRequest")
	proto.RegisterType((*QueryStrengthResponse)(nil), "dreamtree.attest.v1.QueryStrengthResponse")
	proto.RegisterType((*QueryWorkValueRequest)(nil), "dreamtree.attest.v1.QueryWorkValueRequest")
	proto.RegisterType((*QueryWorkValueResponse)(nil), "dreamtree.attest.v1.QueryWorkValueResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "dreamtree.attest.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "dreamtree.attest.v1.QueryParamsResponse")
}

func init() { proto.RegisterFile("dreamtree/attest/v1/query.proto", fileDescriptor_a0bc25296bbe6226) }

var fileDescriptor_a0bc25296bbe6226 = []byte{
	// 889 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0x3a, 0xcd, 0xaf, 0x67, 0x7e, 0xb4, 0x53, 0xb7, 0xac, 0x36, 0xe0, 0x58, 0x0b, 0x24,
	0x8e, 0xd3, 0xec, 0xc8, 0xa9, 0xe0, 0x88, 0xd4, 0x20, 0x95, 0x13, 0xa2, 0x38, 0x82, 0x4a, 0x5c,
	0xa2, 0xf1, 0x7a, 0xb2, 0x59, 0x1a, 0xef, 0xb8, 0x3b, 0xb3, 0x2e, 0x56, 0x88, 0x84, 0x38, 0xf5,
	0x88, 0xe0, 0x8a, 0xb8, 0x21, 0x21, 0x4e, 0x08, 0xf8, 0x23, 0x7a, 0xac, 0xc4, 0x85, 0x13, 0x42,
	0x09, 0x12, 0xff, 0x06, 0xda, 0x99, 0x67, 0x7b, 0xec, 0xac, 0x93, 0x20, 0x71, 0xe0, 0x62, 0xed,
	0x7c, 0xf3, 0xbd, 0xf7, 0xbe, 0xf9, 0x66, 0xde, 0x93, 0x61, 0xad, 0x93, 0x72, 0xd6, 0x55, 0x29,
	0xe7, 0x94, 0x29, 0xc5, 0xa5, 0xa2, 0xfd, 0x26, 0x7d, 0x9c, 0xf1, 0x74, 0x10, 0xf4, 0x52, 0xa1,
	0x04, 0xb9, 0x39, 0x22, 0x04, 0x86, 0x10, 0xf4, 0x9b, 0x5e, 0x23, 0x14, 0xb2, 0x2b, 0x24, 0x6d,
	0x33, 0xc9, 0x0d, 0x9b, 0xf6, 0x9b, 0x6d, 0xae, 0x58, 0x93, 0xf6, 0x58, 0x14, 0x27, 0x4c, 0xc5,
	0x22, 0x31, 0x09, 0xbc, 0x55, 0xe4, 0x0e, 0x69, 0x76, 0x76, 0xef, 0xd5, 0x48, 0x88, 0xe8, 0x88,
	0x53, 0xd6, 0x8b, 0x29, 0x4b, 0x12, 0xa1, 0x74, 0xa4, 0xc4, 0xdd, 0x4a, 0x24, 0x22, 0xa1, 0x3f,
	0x69, 0xfe, 0x85, 0xe8, 0x0d, 0xd6, 0x8d, 0x13, 0x41, 0xf5, 0x2f, 0x42, 0x85, 0xa7, 0x50, 0x83,
	0x1e, 0xc7, 0x4c, 0xfe, 0x26, 0xbc, 0xf2, 0x61, 0x5e, 0xf6, 0x9e, 0xde, 0xd5, 0x45, 0x5a, 0xfc,
	0x71, 0xc6, 0xa5, 0x22, 0x2f, 0x41, 0x29, 0xee, 0xb8, 0x4e, 0xcd, 0xa9, 0x5f, 0x6b, 0x95, 0xe2,
	0x8e, 0x1f, 0x83, 0x7b, 0x9e, 0x2a, 0x7b, 0x22, 0x91, 0x9c, 0xbc, 0x0f, 0x65, 0x36, 0x86, 0x75,
	0x50, 0x79, 0xa7, 0x16, 0x14, 0x58, 0x14, 0x58, 0xe1, 0xbb, 0x2b, 0xcf, 0xfe, 0x58, 0x9b, 0xfb,
	0xe1, 0xef, 0x9f, 0x1a, 0x4e, 0xcb, 0x8e, 0xf7, 0x07, 0x70, 0x4b, 0x97, 0xda, 0x1d, 0xec, 0x65,
	0xed, 0x4f, 0x79, 0xa8, 0x86, 0x9a, 0x5c, 0x58, 0x92, 0x06, 0xd1, 0x35, 0x56, 0x5a, 0xc3, 0x25,
	0xb9, 0x0f, 0x30, 0x76, 0xd8, 0x2d, 0x69, 0x01, 0xeb, 0x81, 0xb1, 0x38, 0xc8, 0xaf, 0x23, 0x30,
	0xf6, 0xe2, 0x75, 0x04, 0x0f, 0x58, 0xc4, 0x31, 0x6b, 0xcb, 0x8a, 0xf4, 0x7f, 0x76, 0xe0, 0xf6,
	0x74, 0x6d, 0x3c, 0xe4, 0x07, 0xf0, 0x82, 0x25, 0x52, 0xba, 0x4e, 0x6d, 0xfe, 0xdf, 0x9e, 0x72,
	0x22, 0x01, 0x79, 0xaf, 0x40, 0xf3, 0xc6, 0xa5, 0x9a, 0x8d, 0x9a, 0x09, 0xd1, 0x9f, 0x8f, 0x34,
	0x9b, 0xba, 0x22, 0x1d, 0x1a, 0xe6, 0xc1, 0x32, 0x43, 0x08, 0x1d, 0x1b, 0xad, 0xff, 0x33, 0xcb,
	0x7e, 0x71, 0xf0, 0x11, 0xd9, 0xe5, 0xff, 0xf7, 0x9e, 0xad, 0x43, 0x45, 0x8b, 0xde, 0x53, 0x29,
	0x4f, 0x22, 0x75, 0x38, 0xeb, 0xd9, 0x3f, 0x2d, 0xe1, 0x63, 0x1c, 0x13, 0xf1, 0x6c, 0x53, 0xcc,
	0xdc, 0x6b, 0x89, 0x1c, 0x2d, 0x6c, 0xa5, 0x35, 0x5a, 0x93, 0x2a, 0x40, 0xca, 0x7b, 0x19, 0xf6,
	0xc7, 0xbc, 0xde, 0xb5, 0x10, 0x52, 0x83, 0xb2, 0xec, 0xf1, 0x30, 0x3e, 0x88, 0xc3, 0x58, 0x0d,
	0xdc, 0x6b, 0x9a, 0x60, 0x43, 0x64, 0x0d, 0xca, 0x79, 0xe3, 0xee, 0x3f, 0xe1, 0x71, 0x74, 0xa8,
	0xdc, 0x05, 0x93, 0x22, 0x87, 0x1e, 0x6a, 0x84, 0x54, 0x60, 0xa1, 0xc3, 0x43, 0x36, 0x70, 0x17,
	0xf5, 0x96, 0x59, 0x90, 0x4d, 0xb8, 0x9e, 0xf2, 0x83, 0x4c, 0xf1, 0xce, 0xfe, 0x41, 0xca, 0x42,
	0x5d, 0x7e, 0x49, 0x13, 0x5e, 0x46, 0xfc, 0x3e, 0xc2, 0x79, 0x05, 0x16, 0xf1, 0x7d, 0xc9, 0x43,
	0x91, 0x74, 0xa4, 0xbb, 0x5c, 0x73, 0xea, 0xf3, 0x2d, 0x60, 0x11, 0xdf, 0x33, 0x88, 0xdf, 0x44,
	0x27, 0x1e, 0x8a, 0xf4, 0xd1, 0xc7, 0xec, 0x28, 0xe3, 0x97, 0xb6, 0xa5, 0x9f, 0xe1, 0xcb, 0xb4,
	0x42, 0xd0, 0xbd, 0xd9, 0xad, 0x5c, 0x81, 0x85, 0x7e, 0x4e, 0x45, 0x13, 0xcd, 0x82, 0x6c, 0xc1,
	0x0d, 0xeb, 0x21, 0xec, 0x87, 0x22, 0x4b, 0x94, 0x36, 0xf2, 0xc5, 0xd6, 0x75, 0x6b, 0xe3, 0xdd,
	0x1c, 0xf7, 0x2b, 0x40, 0x74, 0xd9, 0x07, 0x2c, 0x65, 0x5d, 0x89, 0x32, 0xfd, 0x8f, 0xe0, 0xe6,
	0x04, 0x8a, 0x4a, 0xde, 0x81, 0xc5, 0x9e, 0x46, 0x70, 0x6e, 0xad, 0x16, 0xbe, 0x4e, 0x13, 0x64,
	0x3f, 0x4c, 0x8c, 0xda, 0xf9, 0x75, 0x09, 0x16, 0x74, 0x5e, 0xf2, 0x9d, 0x03, 0x65, 0xeb, 0x15,
	0x93, 0x3b, 0x85, 0x99, 0x66, 0x0c, 0x5c, 0x6f, 0xfb, 0x8a, 0x6c, 0x23, 0xdb, 0xdf, 0x79, 0x9a,
	0xab, 0xf8, 0xf2, 0xb7, 0xbf, 0xbe, 0x29, 0x6d, 0x90, 0x37, 0x69, 0xd1, 0xa4, 0xb7, 0x7c, 0xa1,
	0xc7, 0x71, 0xe7, 0x84, 0x7c, 0xef, 0xc0, 0x2d, 0x2b, 0x97, 0x1c, 0x0d, 0x39, 0xd2, 0x98, 0x5d,
	0x7c, 0x7a, 0x0a, 0x7b, 0x5b, 0x57, 0xe2, 0xa2, 0xcc, 0xbb, 0x63, 0x99, 0x75, 0xb2, 0x5e, 0x28,
	0x13, 0x2f, 0x9e, 0x1e, 0xe3, 0xc7, 0x09, 0xf9, 0xd1, 0x81, 0xdb, 0x93, 0x3a, 0x87, 0x93, 0x85,
	0x5c, 0x58, 0x7c, 0x6a, 0xfc, 0x79, 0x77, 0xae, 0x46, 0x46, 0xa9, 0x6f, 0x8d, 0xa5, 0x36, 0x48,
	0xfd, 0x02, 0x47, 0x45, 0x4a, 0x8f, 0x87, 0x5f, 0x27, 0xe4, 0x6b, 0x07, 0x96, 0x87, 0xc3, 0x81,
	0x6c, 0xce, 0xae, 0x38, 0x35, 0x69, 0xbc, 0xc6, 0x55, 0xa8, 0x28, 0x8d, 0x8e, 0xa5, 0xbd, 0x41,
	0xfc, 0x62, 0x17, 0x31, 0xc6, 0xdc, 0xf4, 0xb7, 0x0e, 0xac, 0x8c, 0x9a, 0xee, 0xa2, 0xdb, 0x9d,
	0x6e, 0xe6, 0x8b, 0x6e, 0xf7, 0x5c, 0x17, 0xfb, 0x6f, 0x8f, 0x75, 0x6d, 0x91, 0xcd, 0x42, 0x5d,
	0x4f, 0x44, 0xfa, 0x68, 0x5b, 0xf7, 0xb0, 0x75, 0xc1, 0x5f, 0x38, 0xb0, 0x68, 0x3a, 0x8a, 0x6c,
	0xcc, 0xae, 0x37, 0xd1, 0xbe, 0x5e, 0xfd, 0x72, 0x22, 0xaa, 0x7a, 0x5d, 0x0b, 0x7a, 0x8d, 0xac,
	0x16, 0x0a, 0x32, 0x6d, 0xbb, 0x7b, 0xef, 0xd9, 0x69, 0xd5, 0x79, 0x7e, 0x5a, 0x75, 0xfe, 0x3c,
	0xad, 0x3a, 0x5f, 0x9d, 0x55, 0xe7, 0x9e, 0x9f, 0x55, 0xe7, 0x7e, 0x3f, 0xab, 0xce, 0x7d, 0xb2,
	0x11, 0xc5, 0xea, 0x30, 0x6b, 0x07, 0xa1, 0xe8, 0xd2, 0xf6, 0x91, 0x48, 0xa2, 0xed, 0x0e, 0xef,
	0x5b, 0xa9, 0x3e, 0xc3, 0x64, 0xed, 0x45, 0xfd, 0x27, 0xea, 0xee, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x05, 0xa2, 0xc0, 0x68, 0x2d, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Attestation(ctx context.Context, in *QueryAttestationRequest, opts ...grpc.CallOption) (*QueryAttestationResponse, error)
	AttestationsBySubject(ctx context.Context, in *QueryBySubjectRequest, opts ...grpc.CallOption) (*QueryBySubjectResponse, error)
	AttestationsByAttestor(ctx context.Context, in *QueryByAttestorRequest, opts ...grpc.CallOption) (*QueryByAttestorResponse, error)
	// Strength returns S(att,t) for one attestation, with its components broken out.
	Strength(ctx context.Context, in *QueryStrengthRequest, opts ...grpc.CallOption) (*QueryStrengthResponse, error)
	// WorkValue returns V(w,t) for a subject — the paper-shape aggregation of the
	// strengths of all non-outcome attestations on it.
	WorkValue(ctx context.Context, in *QueryWorkValueRequest, opts ...grpc.CallOption) (*QueryWorkValueResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Attestation(ctx context.Context, in *QueryAttestationRequest, opts ...grpc.CallOption) (*QueryAttestationResponse, error) {
	out := new(QueryAttestationResponse)
	err := c.cc.Invoke(ctx, "/dreamtree.attest.v1.Query/Attestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AttestationsBySubject(ctx context.Context, in *QueryBySubjectRequest, opts ...grpc.CallOption) (*QueryBySubjectResponse, error) {
	out := new(QueryBySubjectResponse)
	err := c.cc.Invoke(ctx, "/dreamtree.attest.v1.Query/AttestationsBySubject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AttestationsByAttestor(ctx context.Context, in *QueryByAttestorRequest, opts ...grpc.CallOption) (*QueryByAttestorResponse, error) {
	out := new(QueryByAttestorResponse)
	err := c.cc.Invoke(ctx, "/dreamtree.attest.v1.Query/AttestationsByAttestor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Strength(ctx context.Context, in *QueryStrengthRequest, opts ...grpc.CallOption) (*QueryStrengthResponse, error) {
	out := new(QueryStrengthResponse)
	err := c.cc.Invoke(ctx, "/dreamtree.attest.v1.Query/Strength", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WorkValue(ctx context.Context, in *QueryWorkValueRequest, opts ...grpc.CallOption) (*QueryWorkValueResponse, error) {
	out := new(QueryWorkValueResponse)
	err := c.cc.Invoke(ctx, "/dreamtree.attest.v1.Query/WorkValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/dreamtree.attest.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Attestation(context.Context, *QueryAttestationRequest) (*QueryAttestationResponse, error)
	AttestationsBySubject(context.Context, *QueryBySubjectRequest) (*QueryBySubjectResponse, error)
	AttestationsByAttestor(context.Context, *QueryByAttestorRequest) (*QueryByAttestorResponse, error)
	// Strength returns S(att,t) for one attestation, with its components broken out.
	Strength(context.Context, *QueryStrengthRequest) (*QueryStrengthResponse, error)
	// WorkValue returns V(w,t) for a subject — the paper-shape aggregation of the
	// strengths of all non-outcome attestations on it.
	WorkValue(context.Context, *QueryWorkValueRequest) (*QueryWorkValueResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Attestation(ctx context.Context, req *QueryAttestationRequest) (*QueryAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attestation not implemented")
}
func (*UnimplementedQueryServer) AttestationsBySubject(ctx context.Context, req *QueryBySubjectRequest) (*QueryBySubjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestationsBySubject not implemented")
}
func (*UnimplementedQueryServer) AttestationsByAttestor(ctx context.Context, req *QueryByAttestorRequest) (*QueryByAttestorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestationsByAttestor not implemented")
}
func (*UnimplementedQueryServer) Strength(ctx context.Context, req *QueryStrengthRequest) (*QueryStrengthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Strength not implemented")
}
func (*UnimplementedQueryServer) WorkValue(ctx context.Context, req *QueryWorkValueRequest) (*QueryWorkValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkValue not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Attestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Attestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamtree.attest.v1.Query/Attestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Attestation(ctx, req.(*QueryAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AttestationsBySubject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBySubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AttestationsBySubject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamtree.attest.v1.Query/AttestationsBySubject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AttestationsBySubject(ctx, req.(*QueryBySubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AttestationsByAttestor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByAttestorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AttestationsByAttestor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamtree.attest.v1.Query/AttestationsByAttestor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AttestationsByAttestor(ctx, req.(*QueryByAttestorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Strength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStrengthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Strength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamtree.attest.v1.Query/Strength",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Strength(ctx, req.(*QueryStrengthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WorkValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWorkValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WorkValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamtree.attest.v1.Query/WorkValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WorkValue(ctx, req.(*QueryWorkValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dreamtree.attest.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dreamtree.attest.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Attestation",
			Handler:    _Query_Attestation_Handler,
		},
		{
			MethodName: "AttestationsBySubject",
			Handler:    _Query_AttestationsBySubject_Handler,
		},
		{
			MethodName: "AttestationsByAttestor",
			Handler:    _Query_AttestationsByAttestor_Handler,
		},
		{
			MethodName: "Strength",
			Handler:    _Query_Strength_Handler,
		},
		{
			MethodName: "WorkValue",
			Handler:    _Query_WorkValue_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dreamtree/attest/v1/query.proto",
}

func (m *QueryAttestationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAttestationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Attestation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBySubjectRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBySubjectRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBySubjectRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBySubjectResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBySubjectResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBySubjectResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryByAttestorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryByAttestorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryByAttestorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Attestor) > 0 {
		i -= len(m.Attestor)
		copy(dAtA[i:], m.Attestor)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Attestor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryByAttestorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryByAttestorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryByAttestorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryStrengthRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStrengthRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStrengthRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryStrengthResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStrengthResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStrengthResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AgeSeconds != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AgeSeconds))
		i--
		dAtA[i] = 0x40
	}
	if len(m.RefutedFraction) > 0 {
		i -= len(m.RefutedFraction)
		copy(dAtA[i:], m.RefutedFraction)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RefutedFraction)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Decay) > 0 {
		i -= len(m.Decay)
		copy(dAtA[i:], m.Decay)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Decay)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TypeWeight) > 0 {
		i -= len(m.TypeWeight)
		copy(dAtA[i:], m.TypeWeight)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TypeWeight)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Specificity) > 0 {
		i -= len(m.Specificity)
		copy(dAtA[i:], m.Specificity)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Specificity)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Reputation) > 0 {
		i -= len(m.Reputation)
		copy(dAtA[i:], m.Reputation)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Reputation)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Strength) > 0 {
		i -= len(m.Strength)
		copy(dAtA[i:], m.Strength)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Strength)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryWorkValueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWorkValueRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWorkValueRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWorkValueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWorkValueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWorkValueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AttestationCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AttestationCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Subject) > 0 {
		i -= len(m.Subject)
		copy(dAtA[i:], m.Subject)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Subject)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAttestationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryAttestationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Attestation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBySubjectRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBySubjectResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryByAttestorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Attestor)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryByAttestorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryStrengthRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryStrengthResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	l = len(m.Strength)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Reputation)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Specificity)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.TypeWeight)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Decay)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RefutedFraction)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AgeSeconds != 0 {
		n += 1 + sovQuery(uint64(m.AgeSeconds))
	}
	return n
}

func (m *QueryWorkValueRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWorkValueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Subject)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AttestationCount != 0 {
		n += 1 + sovQuery(uint64(m.AttestationCount))
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAttestationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Attestation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBySubjectRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBySubjectRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBySubjectRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBySubjectResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBySubjectResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBySubjectResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, Attestation{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryByAttestorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryByAttestorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryByAttestorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryByAttestorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryByAttestorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryByAttestorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, Attestation{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStrengthRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStrengthRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStrengthRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStrengthResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStrengthResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStrengthResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strength", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Strength = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reputation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reputation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Specificity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Specificity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TypeWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TypeWeight = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decay", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Decay = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefutedFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefutedFraction = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgeSeconds", wireType)
			}
			m.AgeSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgeSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWorkValueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWorkValueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWorkValueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWorkValueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWorkValueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWorkValueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subject = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttestationCount", wireType)
			}
			m.AttestationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttestationCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
